cumbia-qtcontrols-ng: EditSourceWidget Class Reference
EditSourceWidget Class Reference
#include <editsourcewidget.h>
Public Member Functions
EditSourceWidget (int index, QWidget *parent=nullptr)
QString source () const
void setSource (const QString &s)
bool checkSource ()
EditSourceWidget (int index, QWidget *parent=nullptr)
QString source () const
void setSource (const QString &s)
bool checkSource ()
Protected Slots
void loadFromJs ()
void onFormulaEnabled (bool en)
void expressionValid ()
void loadFromJs ()
void onFormulaEnabled (bool en)
void expressionValid ()
Constructor & Destructor Documentation
EditSourceWidget() [1/2]
EditSourceWidget::EditSourceWidget (int index, QWidget * parent = nullptr) explicit
References expressionValid(), loadFromJs(), and onFormulaEnabled().
EditSourceWidget() [2/2]
EditSourceWidget::EditSourceWidget (int index, QWidget * parent = nullptr) explicit
Member Function Documentation
checkSource() [1/2]
bool EditSourceWidget::checkSource ()
Referenced by EditSourceDialog::checkSource().
checkSource() [2/2]
bool EditSourceWidget::checkSource ()
expressionValid [1/2]
void EditSourceWidget::expressionValid () protected slot
Referenced by EditSourceWidget(), and loadFromJs().
expressionValid [2/2]
void EditSourceWidget::expressionValid () protected slot
loadFromJs [1/2]
void EditSourceWidget::loadFromJs () protected slot
References expressionValid().
Referenced by EditSourceWidget().
loadFromJs [2/2]
void EditSourceWidget::loadFromJs () protected slot
onFormulaEnabled [1/2]
void EditSourceWidget::onFormulaEnabled (bool en) protected slot
Referenced by EditSourceWidget().
onFormulaEnabled [2/2]
void EditSourceWidget::onFormulaEnabled (bool en) protected slot
setSource() [1/2]
void EditSourceWidget::setSource (const QString & s)
setSource() [2/2]
void EditSourceWidget::setSource (const QString & s)
source() [1/2]
QString EditSourceWidget::source () const
References perr, and qstoc.
source() [2/2]
QString EditSourceWidget::source () const
The documentation for this class was generated from the following files:
base/cumbia-qtcontrols-ng-base-designer/forms/editsourcewidget.h
controls/cumbia-qtcontrols-ng-controls-designer/forms/editsourcewidget.h
base/cumbia-qtcontrols-ng-base-designer/forms/editsourcewidget.cpp
controls/cumbia-qtcontrols-ng-controls-designer/forms/editsourcewidget.cpp