cumbia-qtcontrols-ng: QuZoomEvents Class Reference
QuZoomEvents Class Reference
#include <quzoomevents.h>
Public Types
enum Operation { Zoom = 0 , Move , EndOps }
Signals
void zoomRectChanged (const QRectF &r)
void unzoom ()
void moveRect (const QPointF &p1, const QPointF &p2)
void zoomRectChanging (const QPointF &topl, const QPointF br)
void clicked (const QPointF &pos, Qt::MouseButton button, Qt::KeyboardModifiers m)
Public Member Functions
QuZoomEvents (QObject *parent)
virtual ~QuZoomEvents ()
void setKeyboardModifier (Operation op, Qt::KeyboardModifier mod)
Qt::KeyboardModifier keyboardModifier (Operation op) const
bool eventFilter (QObject *watched, QEvent *event)
Public Attributes
QPointF p1
QPointF p2
Member Enumeration Documentation
Operation
enum QuZoomEvents::Operation
Enumerator
Zoom
Move
EndOps
Constructor & Destructor Documentation
QuZoomEvents()
QuZoomEvents::QuZoomEvents (QObject * parent) explicit
~QuZoomEvents()
QuZoomEvents::~QuZoomEvents () virtual
Member Function Documentation
clicked
void QuZoomEvents::clicked (const QPointF & pos, Qt::MouseButton button, Qt::KeyboardModifiers m) signal
Referenced by eventFilter().
eventFilter()
bool QuZoomEvents::eventFilter (QObject * watched, QEvent * event)
References clicked(), Move, moveRect(), p1, p2, perr, unzoom(), Zoom, zoomRectChanged(), and zoomRectChanging().
keyboardModifier()
Qt::KeyboardModifier QuZoomEvents::keyboardModifier (Operation op) const
References EndOps.
moveRect
void QuZoomEvents::moveRect (const QPointF & p1, const QPointF & p2) signal
Referenced by eventFilter().
setKeyboardModifier()
void QuZoomEvents::setKeyboardModifier (Operation op, Qt::KeyboardModifier mod)
References EndOps.
unzoom
void QuZoomEvents::unzoom () signal
Referenced by eventFilter().
zoomRectChanged
void QuZoomEvents::zoomRectChanged (const QRectF & r) signal
Referenced by eventFilter().
zoomRectChanging
void QuZoomEvents::zoomRectChanging (const QPointF & topl, const QPointF br) signal
Referenced by eventFilter().
Member Data Documentation
p1
QPointF QuZoomEvents::p1
Referenced by eventFilter().
p2
QPointF QuZoomEvents::p2
Referenced by eventFilter().
The documentation for this class was generated from the following files:
quzoomevents.h
quzoomevents.cpp