cumbia-qtcontrols-ng: QuCircularPlotDrawable_I Class Reference
QuCircularPlotDrawable_I Class Reference abstract
#include <qucircularplot_drawable_i.h>
Public Member Functions
virtual bool scales ()=0
returns true if the drawable scales with zooming
virtual int z () const =0
z defines the z order of the element that is drawn
virtual void draw (QPainter *p, const QuCircularPlotEngine *plot_e, double inner_radius, double outer_radius, const QRectF &rect, QWidget *widget)=0
paint the drawable on the provided painter.
Member Function Documentation
draw()
virtual void QuCircularPlotDrawable_I::draw (QPainter * p, const QuCircularPlotEngine * plot_e, double inner_radius, double outer_radius, const QRectF & rect, QWidget * widget) pure virtual
paint the drawable on the provided painter.
Draw a custom shape on the painter. The plot engine can be used to get the plot configuration
Note
Inner and outer radiuses correspond to the axes bounds. The valid area for curves is defined between the inner_radius and the outer_radius. Outside this section, curves may be drawn deformed.
Drawables can paint anywhere.
Parameters
p the active painter
plot_e the plot engine
inner_radius start of valid scale section
outer_radius end of valid scale section
rect the drawing area, directly from QGraphicsItem::paint
widget pointer to QWidget, directly from QGraphicsItem::paint
Implemented in QuCircularPlotDiskSector, and QuCircularPlotSelectionValue.
Referenced by QuCircularPlotEngine::paint().
scales()
virtual bool QuCircularPlotDrawable_I::scales () pure virtual
returns true if the drawable scales with zooming
Returns
true the drawable scales according to the zoom. It will be painted with the painter transform applied false the drawable does not scale with the zoom. It will be painted after the painter is restored or before the transformation is applied, according to the z value
See also
z
Implemented in QuCircularPlotDiskSector, and QuCircularPlotSelectionValue.
Referenced by QuCircularPlotEngine::paint().
z()
virtual int QuCircularPlotDrawable_I::z () const pure virtual
z defines the z order of the element that is drawn
Returns
the z order
Drawable elements with a lower z value are drawn before.
Important note
Axes, curves, baseline and bounds are assumed to have z equal to 0. Drawables with z less than or equal to 0 will be drawn before the axes and the curves. Drawables with z greater than zero will be drawn after axes, bounds and curves.
Implemented in QuCircularPlotDiskSector, and QuCircularPlotSelectionValue.
Referenced by QuCircularPlotEngine::addDrawable(), and QuCircularPlotEngine::paint().
The documentation for this class was generated from the following file:
qucircularplot_drawable_i.h