cumbia-qtcontrols-ng: QGraphicsZoomer Class Reference
QGraphicsZoomer Class Reference
#include <qgraphicszoomer.h>
Public Member Functions
QGraphicsZoomer (QGraphicsPlotItem *plot)
void addScale (ScaleItem *scale)
void removeScale (ScaleItem *scale)
virtual ~QGraphicsZoomer ()
void zoom (const QRectF &zoomRect)
zoom the axes according to the zoomRect given in view coordinates
bool inZoom () const
void unzoom ()
void clear ()
int stackSize () const
void plotAreaChanged (const QRectF &newRect)
notifies when the canvas area changes.
void xAxisBoundsChanged (double, double)
x axis bounds notification
void yAxisBoundsChanged (double, double)
y axis bounds notification
void axisAutoscaleChanged (ScaleItem::Orientation o, bool as)
x axis auto scale property change notification
virtual void tickStepLenChanged (double)
notifies listeners about tick step len changes.
virtual void labelsFormatChanged (const QString &)
when the labels format changes, labelsFormatChanged is used
ScaleItem * xAxis () const
Returns ScaleItem::xBottom if set.
ScaleItem * yAxis () const
Public Member Functions inherited from AxisChangeListener
AxisChangeListener ()
virtual void xAxisBoundsChanged (double lower, double upper)=0
x axis bounds notification
virtual void yAxisBoundsChanged (double lower, double upper)=0
y axis bounds notification
virtual void axisAutoscaleChanged (ScaleItem::Orientation o, bool autoscale)=0
x axis auto scale property change notification
virtual void plotAreaChanged (const QRectF &newRect)=0
notifies when the canvas area changes.
virtual void tickStepLenChanged (double value)=0
notifies listeners about tick step len changes.
virtual void labelsFormatChanged (const QString &newFormat)=0
when the labels format changes, labelsFormatChanged is used
Constructor & Destructor Documentation
QGraphicsZoomer()
QGraphicsZoomer::QGraphicsZoomer (QGraphicsPlotItem * plot) explicit
~QGraphicsZoomer()
QGraphicsZoomer::~QGraphicsZoomer () virtual
References ScaleItem::removeAxisChangeListener().
Member Function Documentation
addScale()
void QGraphicsZoomer::addScale (ScaleItem * scale)
References ScaleItem::installAxisChangeListener().
axisAutoscaleChanged()
void QGraphicsZoomer::axisAutoscaleChanged (ScaleItem::Orientation o, bool autoscale) virtual
x axis auto scale property change notification
Parameters
o the ScaleItem::Orientation property that helps you find out which axis (x or y) has changed its property.
autoscale true autoscale is enabled.
autoscale false autoscale is disabled.
Implements AxisChangeListener.
clear()
void QGraphicsZoomer::clear ()
References unzoom().
inZoom()
bool QGraphicsZoomer::inZoom () const
labelsFormatChanged()
virtual void QGraphicsZoomer::labelsFormatChanged (const QString & newFormat) inline virtual
when the labels format changes, labelsFormatChanged is used
See also
ScaleItem
Implements AxisChangeListener.
plotAreaChanged()
void QGraphicsZoomer::plotAreaChanged (const QRectF & newRect) virtual
notifies when the canvas area changes.
In some cases, when the axis is placed on the right or at the bottom of the plot, the labels might require more space, and the plot area must be reduced.
Parameters
newRect the new rectangle
d_ptr->zoomStack[0] = newRect;
Implements AxisChangeListener.
removeScale()
void QGraphicsZoomer::removeScale (ScaleItem * scale)
References ScaleItem::removeAxisChangeListener().
stackSize()
int QGraphicsZoomer::stackSize () const
tickStepLenChanged()
virtual void QGraphicsZoomer::tickStepLenChanged (double value) inline virtual
notifies listeners about tick step len changes.
The tick step len can be tuned by a property in a ScaleItem or let it be automatically calculated by ScaleItem.
See also
ScaleItem
Implements AxisChangeListener.
unzoom()
void QGraphicsZoomer::unzoom ()
References ScaleItem::setBounds().
Referenced by clear().
xAxis()
ScaleItem * QGraphicsZoomer::xAxis () const
Returns ScaleItem::xBottom if set.
References ScaleItem::axisId(), and ScaleItem::xBottom.
xAxisBoundsChanged()
void QGraphicsZoomer::xAxisBoundsChanged (double lower, double upper) inline virtual
x axis bounds notification
Parameters
lower the new lower bound
upper the new upper bound
Implements AxisChangeListener.
yAxis()
ScaleItem * QGraphicsZoomer::yAxis () const
References ScaleItem::axisId(), and ScaleItem::yLeft.
yAxisBoundsChanged()
void QGraphicsZoomer::yAxisBoundsChanged (double lower, double upper) inline virtual
y axis bounds notification
Parameters
lower the new lower bound
upper the new upper bound
Implements AxisChangeListener.
zoom()
void QGraphicsZoomer::zoom (const QRectF & zoomRect)
zoom the axes according to the zoomRect given in view coordinates
Parameters
zoomRect rectangle in view coordinates
References ScaleItem::Horizontal, ScaleItem::lowerBound, ScaleItem::orientation(), ScaleItem::setBounds(), and ScaleItem::upperBound.
The documentation for this class was generated from the following files:
qgraphicszoomer.h
qgraphicszoomer.cpp