cumbia-qtcontrols-ng: AxisChangeListener Class Reference
AxisChangeListener Class Reference abstract
A listener for axis change events.
#include <axischangelistener.h>
Public Member Functions
AxisChangeListener ()
virtual void xAxisBoundsChanged (double lower, double upper)=0
x axis bounds notification
virtual void yAxisBoundsChanged (double lower, double upper)=0
y axis bounds notification
virtual void axisAutoscaleChanged (ScaleItem::Orientation o, bool autoscale)=0
x axis auto scale property change notification
virtual void plotAreaChanged (const QRectF &newRect)=0
notifies when the canvas area changes.
virtual void tickStepLenChanged (double value)=0
notifies listeners about tick step len changes.
virtual void labelsFormatChanged (const QString &newFormat)=0
when the labels format changes, labelsFormatChanged is used
Detailed Description
A listener for axis change events.
Implement this interface in a subclass in order to receive ScaleItem events, such as bound changes and auto scale property changes.
Install your object by calling ScaleItem::installAxisChangeListener
Constructor & Destructor Documentation
AxisChangeListener()
AxisChangeListener::AxisChangeListener () inline
Member Function Documentation
axisAutoscaleChanged()
virtual void AxisChangeListener::axisAutoscaleChanged (ScaleItem::Orientation o, bool autoscale) pure virtual
x axis auto scale property change notification
Parameters
o the ScaleItem::Orientation property that helps you find out which axis (x or y) has changed its property.
autoscale true autoscale is enabled.
autoscale false autoscale is disabled.
Implemented in QGraphicsZoomer, SceneCurve, ExternalScaleWidget, and TargetItem.
Referenced by ScaleItem::installAxisChangeListener(), and ScaleItem::setAxisAutoscaleEnabled().
labelsFormatChanged()
virtual void AxisChangeListener::labelsFormatChanged (const QString & newFormat) pure virtual
when the labels format changes, labelsFormatChanged is used
See also
ScaleItem
Implemented in SceneCurve, TargetItem, QGraphicsZoomer, and ExternalScaleWidget.
Referenced by ScaleItem::installAxisChangeListener(), and ScaleItem::updateLabelsFormat().
plotAreaChanged()
virtual void AxisChangeListener::plotAreaChanged (const QRectF & newRect) pure virtual
notifies when the canvas area changes.
In some cases, when the axis is placed on the right or at the bottom of the plot, the labels might require more space, and the plot area must be reduced.
Parameters
newRect the new rectangle
Implemented in SceneCurve, ExternalScaleWidget, TargetItem, and QGraphicsZoomer.
Referenced by ScaleItem::installAxisChangeListener(), and ScaleItem::paint().
tickStepLenChanged()
virtual void AxisChangeListener::tickStepLenChanged (double value) pure virtual
notifies listeners about tick step len changes.
The tick step len can be tuned by a property in a ScaleItem or let it be automatically calculated by ScaleItem.
See also
ScaleItem
Implemented in ExternalScaleWidget, SceneCurve, TargetItem, and QGraphicsZoomer.
Referenced by ScaleItem::installAxisChangeListener(), ScaleItem::setTickStepLen(), and ScaleItem::updateStepLen().
xAxisBoundsChanged()
virtual void AxisChangeListener::xAxisBoundsChanged (double lower, double upper) pure virtual
x axis bounds notification
Parameters
lower the new lower bound
upper the new upper bound
Implemented in ExternalScaleWidget, SceneCurve, TargetItem, and QGraphicsZoomer.
Referenced by ScaleItem::installAxisChangeListener(), ScaleItem::mNotifyBoundsChanged(), and ScaleItem::setBoundsFromCurves().
yAxisBoundsChanged()
virtual void AxisChangeListener::yAxisBoundsChanged (double lower, double upper) pure virtual
y axis bounds notification
Parameters
lower the new lower bound
upper the new upper bound
Implemented in ExternalScaleWidget, SceneCurve, TargetItem, and QGraphicsZoomer.
Referenced by ScaleItem::installAxisChangeListener(), ScaleItem::mNotifyBoundsChanged(), and ScaleItem::setBoundsFromCurves().
The documentation for this class was generated from the following file:
axischangelistener.h