cumbia-qtcontrols-ng: CurveChangeListener Class Reference
CurveChangeListener Class Reference abstract
#include <curvechangelistener.h>
Public Member Functions
CurveChangeListener ()
virtual QRectF itemAdded (const Point &pt)=0
virtual int itemAboutToBeRemoved (const Point &pt)=0
virtual QRectF itemRemoved (const Point &pt)=0
virtual void fullVectorUpdate ()=0
virtual void bufferSizeChanged (int newSize)=0
virtual void minXChanged (double min)=0
virtual void maxXChanged (double max)=0
virtual void minYChanged (double min)=0
virtual void maxYChanged (double max)=0
virtual void affectingBoundsPointsRemoved ()=0
Constructor & Destructor Documentation
CurveChangeListener()
CurveChangeListener::CurveChangeListener () inline
Member Function Documentation
affectingBoundsPointsRemoved()
virtual void CurveChangeListener::affectingBoundsPointsRemoved () pure virtual
Implemented in CurveItem.
bufferSizeChanged()
virtual void CurveChangeListener::bufferSizeChanged (int newSize) pure virtual
Implemented in CurveItem.
Referenced by SceneCurve::setBufferSize().
fullVectorUpdate()
virtual void CurveChangeListener::fullVectorUpdate () pure virtual
Implemented in CurveItem.
Referenced by SceneCurve::setData().
itemAboutToBeRemoved()
virtual int CurveChangeListener::itemAboutToBeRemoved (const Point & pt) pure virtual
Implemented in CurveItem.
itemAdded()
virtual QRectF CurveChangeListener::itemAdded (const Point & pt) pure virtual
Implemented in CurveItem.
Referenced by SceneCurve::addPoint().
itemRemoved()
virtual QRectF CurveChangeListener::itemRemoved (const Point & pt) pure virtual
Implemented in CurveItem.
maxXChanged()
virtual void CurveChangeListener::maxXChanged (double max) pure virtual
Implemented in CurveItem.
maxYChanged()
virtual void CurveChangeListener::maxYChanged (double max) pure virtual
Implemented in CurveItem.
minXChanged()
virtual void CurveChangeListener::minXChanged (double min) pure virtual
Implemented in CurveItem.
minYChanged()
virtual void CurveChangeListener::minYChanged (double min) pure virtual
Implemented in CurveItem.
The documentation for this class was generated from the following file:
curvechangelistener.h