cumbia-qtcontrols-ng: QuCircularPlotCurveSelectionEvents Class Reference
QuCircularPlotCurveSelectionEvents Class Reference
#include <qucircularplotcurveselectionevents.h>
Public Slots
void setTransform (const QTransform &T)
Signals
void selected (const QPointF &p)
void selectionMoved (const double &dx, const double &dy)
void deselected ()
Public Member Functions
QuCircularPlotCurveSelectionEvents (QObject *parent=nullptr)
virtual ~QuCircularPlotCurveSelectionEvents ()
bool eventFilter (QObject *watched, QEvent *event)
void select (const QRectF &r)
const QRectF & selectionArea () const
Constructor & Destructor Documentation
QuCircularPlotCurveSelectionEvents()
QuCircularPlotCurveSelectionEvents::QuCircularPlotCurveSelectionEvents (QObject * parent = nullptr) explicit
~QuCircularPlotCurveSelectionEvents()
QuCircularPlotCurveSelectionEvents::~QuCircularPlotCurveSelectionEvents () virtual
Member Function Documentation
deselected
void QuCircularPlotCurveSelectionEvents::deselected () signal
Referenced by eventFilter().
eventFilter()
bool QuCircularPlotCurveSelectionEvents::eventFilter (QObject * watched, QEvent * event)
References deselected(), selected(), and selectionMoved().
select()
void QuCircularPlotCurveSelectionEvents::select (const QRectF & r)
Referenced by QuCircularPlotEngine::clearSelection(), QuCircularPlotEngine::moveSelection(), and QuCircularPlotEngine::select().
selected
void QuCircularPlotCurveSelectionEvents::selected (const QPointF & p) signal
Referenced by eventFilter().
selectionArea()
const QRectF & QuCircularPlotCurveSelectionEvents::selectionArea () const
Referenced by QuCircularPlotEngine::moveSelection().
selectionMoved
void QuCircularPlotCurveSelectionEvents::selectionMoved (const double & dx, const double & dy) signal
Referenced by eventFilter().
setTransform
void QuCircularPlotCurveSelectionEvents::setTransform (const QTransform & T) slot
The documentation for this class was generated from the following files:
qucircularplotcurveselectionevents.h
qucircularplotcurveselectionevents.cpp