cumbia-qtcontrols-ng: CurveItem Class Reference
CurveItem Class Reference
A QGraphicsObject that allows an implementation of the ItemPainterInterface to draw on a PlotSceneWidget. If an ItemPainterInterface (or more) is installed, then the draw method of the ItemPainterInterface is invoked instead of the default paint method.
#include <curveitem.h>
Public Member Functions
CurveItem (SceneCurve *curve, QGraphicsItem *parent)
The constructor of this QGraphicsObject that connects the elements of the associated SceneCurve by means of lines.
virtual ~CurveItem ()
SceneCurve * sceneCurve () const
virtual QRectF boundingRect () const
virtual void itemAboutToBeAdded (const Point &)
virtual QRectF itemAdded (const Point &pt)
virtual int itemAboutToBeRemoved (const Point &pt)
virtual QRectF itemRemoved (const Point &)
virtual void bufferSizeChanged (int)
virtual void minXChanged (double)
virtual void maxXChanged (double)
virtual void minYChanged (double)
virtual void maxYChanged (double)
virtual void fullVectorUpdate ()
virtual void affectingBoundsPointsRemoved ()
void installItemPainterInterface (ItemPainterInterface *itemPainterInterface)
void removeItemPainterInterface (ItemPainterInterface *itemPainterInterface)
QList< ItemPainterInterface * > itemPainters () const
ItemPainterInterface * itemPainter () const
If only one ItemPainterInterface was used, then use this method to retrieve a reference to it.
Public Member Functions inherited from CurveChangeListener
CurveChangeListener ()
virtual QRectF itemAdded (const Point &pt)=0
virtual int itemAboutToBeRemoved (const Point &pt)=0
virtual QRectF itemRemoved (const Point &pt)=0
virtual void fullVectorUpdate ()=0
virtual void bufferSizeChanged (int newSize)=0
virtual void minXChanged (double min)=0
virtual void maxXChanged (double max)=0
virtual void minYChanged (double min)=0
virtual void maxYChanged (double max)=0
virtual void affectingBoundsPointsRemoved ()=0
Protected Member Functions
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
draws the lines connecting the XYItems in the associated curve
Properties
bool visible
qreal zValue
Detailed Description
A QGraphicsObject that allows an implementation of the ItemPainterInterface to draw on a PlotSceneWidget. If an ItemPainterInterface (or more) is installed, then the draw method of the ItemPainterInterface is invoked instead of the default paint method.
See also
ItemPainterInterface
SceneCurve
PlotSceneWidget
The CurveItem class calculates the necessary transformations that allow to correctly map the real data values to the plot canvas coordinates. It makes use of classes implementing the ItemPainterInterface interface in order to draw the data on the plot canvas.
Example
Read the SceneCurve documentation for an example.
Item painters ownership
The CurveItem takes the ownership of every installed ItemPainterInterface implementation instance. This means that all the installed ItemPainterInterface objects are deleted on CurveItem deletion.
CurveItem ownership
If you call PlotSceneWidget::removeCurve, then the associated CurveItem is deleted. If you delete a SceneCurve without invoking PlotSceneWidget::removeCurve (bad), then the associated CurveItem is deleted again for you. This means that once installed on a SceneCurve, the ownership of the CurveItem is taken by the SceneCurve. With the term install we mean the
CurveItem *curveItem = new CurveItem(curve);
instruction.
Constructor & Destructor Documentation
CurveItem()
CurveItem::CurveItem (SceneCurve * curve, QGraphicsItem * parent)
The constructor of this QGraphicsObject that connects the elements of the associated SceneCurve by means of lines.
Parameters
curve the associated SceneCurve
See also
SceneCurve
~CurveItem()
CurveItem::~CurveItem () virtual
Member Function Documentation
affectingBoundsPointsRemoved()
virtual void CurveItem::affectingBoundsPointsRemoved () inline virtual
Implements CurveChangeListener.
boundingRect()
QRectF CurveItem::boundingRect () const virtual
Referenced by paint().
bufferSizeChanged()
virtual void CurveItem::bufferSizeChanged (int) inline virtual
Implements CurveChangeListener.
fullVectorUpdate()
void CurveItem::fullVectorUpdate () virtual
Implements CurveChangeListener.
installItemPainterInterface()
void CurveItem::installItemPainterInterface (ItemPainterInterface * itemPainterInterface)
Referenced by CircleItemSet::CircleItemSet(), DotsPainter::DotsPainter(), HistogramPainter::HistogramPainter(), LinePainter::LinePainter(), and StepsPainter::StepsPainter().
itemAboutToBeAdded()
virtual void CurveItem::itemAboutToBeAdded (const Point &) inline virtual
itemAboutToBeRemoved()
int CurveItem::itemAboutToBeRemoved (const Point & pt) virtual
Implements CurveChangeListener.
References ItemPainterInterface::elementSize(), Data::size(), Data::xData, and Data::yData.
itemAdded()
QRectF CurveItem::itemAdded (const Point & pt) virtual
Implements CurveChangeListener.
References ItemPainterInterface::elementSize(), ScaleItem::lowerBound, Data::size(), ScaleItem::upperBound, Data::xData, and Data::yData.
itemPainter()
ItemPainterInterface * CurveItem::itemPainter () const
If only one ItemPainterInterface was used, then use this method to retrieve a reference to it.
Referenced by LegendItem::getColor().
itemPainters()
QList< ItemPainterInterface * > CurveItem::itemPainters () const
itemRemoved()
QRectF CurveItem::itemRemoved (const Point &) virtual
Implements CurveChangeListener.
maxXChanged()
virtual void CurveItem::maxXChanged (double) inline virtual
Implements CurveChangeListener.
maxYChanged()
virtual void CurveItem::maxYChanged (double) inline virtual
Implements CurveChangeListener.
minXChanged()
virtual void CurveItem::minXChanged (double) inline virtual
Implements CurveChangeListener.
minYChanged()
virtual void CurveItem::minYChanged (double) inline virtual
Implements CurveChangeListener.
paint()
void CurveItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0) protected virtual
draws the lines connecting the XYItems in the associated curve
References boundingRect(), ItemPainterInterface::draw(), and perr.
removeItemPainterInterface()
void CurveItem::removeItemPainterInterface (ItemPainterInterface * itemPainterInterface)
Referenced by CircleItemSet::~CircleItemSet().
sceneCurve()
SceneCurve * CurveItem::sceneCurve () const
Property Documentation
visible
bool CurveItem::visible read write
zValue
qreal CurveItem::zValue read write
The documentation for this class was generated from the following files:
curveitem.h
curveitem.cpp