cumbia-qtcontrols-ng: QuNumericControlW Class Reference
QuNumericControlW Class Reference
A widget to input a number and write it to a target linked to a control system engine.
#include <qunumericcontrol_w.h>
Public Slots
void setTarget (const QString &target)
Set the name of the target that will be executed.
virtual void execute (double val)
executes the target specified with setTarget, writing the value set on the widget.
void onAnimationValueChanged (const QVariant &v)
Public Slots inherited from QuNumericW
void setValue (double v)
void setShowApply (bool s)
void setMaximum (double v)
void setMinimum (double v)
void setIntDigits (int i)
void setDecDigits (int d)
Public Member Functions
QuNumericControlW (QWidget *parent, Cumbia *cumbia, const CuControlsWriterFactoryI &w_fac)
Constructor with the parent widget, an engine specific Cumbia implementation and a CuControlsWriterFactoryI interface.
QuNumericControlW (QWidget *w, CumbiaPool *cumbia_pool, const CuControlsFactoryPool &fpool)
Constructor with the parent widget, CumbiaPool and CuControlsFactoryPool
virtual ~QuNumericControlW ()
class destructor
QString target () const
returns the target name.
void onUpdate (const CuData &d)
configures the widget as soon as it is connected and records write errors.
CuContext * getContext () const
returns a pointer to the context
Public Member Functions inherited from QuNumericW
QuNumericW (QWidget *parent=nullptr)
virtual ~QuNumericW ()
QSize sizeHint () const
QSize minimumSizeHint () const
double maximum () const
double value () const
double minimum () const
int intDigits () const
int decDigits () const
bool showApply () const
Properties
QString target
Properties inherited from QuNumericW
int intDigits
int decDigits
double value
double maximum
double minimum
bool showApply
Additional Inherited Members
Signals inherited from QuNumericW
void valueChanged (double v)
void minimumChanged (double m)
void maximumChanged (double M)
void intDigitsChanged (int id)
void decDigitsChanged (int dd)
void clicked (double val)
Protected Member Functions inherited from QuNumericW
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void mouseDoubleClickEvent (QMouseEvent *event)
void mouseMoveEvent (QMouseEvent *event)
void wheelEvent (QWheelEvent *event)
void leaveEvent (QEvent *event)
void paintEvent (QPaintEvent *event)
void changeEvent (QEvent *e)
Detailed Description
A widget to input a number and write it to a target linked to a control system engine.
Constructor & Destructor Documentation
QuNumericControlW() [1/2]
QuNumericControlW::QuNumericControlW (QWidget * parent, Cumbia * cumbia, const CuControlsWriterFactoryI & w_fac)
Constructor with the parent widget, an engine specific Cumbia implementation and a CuControlsWriterFactoryI interface.
Please refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
QuNumericControlW() [2/2]
QuNumericControlW::QuNumericControlW (QWidget * parent, CumbiaPool * cumbia_pool, const CuControlsFactoryPool & fpool)
Constructor with the parent widget, CumbiaPool and CuControlsFactoryPool
Please refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
~QuNumericControlW()
QuNumericControlW::~QuNumericControlW () virtual
class destructor
Deletes the context used to link the widget to the writer.
Member Function Documentation
execute
void QuNumericControlW::execute (double val) virtual slot
executes the target specified with setTarget, writing the value set on the widget.
The value set on the widget is written on the target when the apply button is clicked. This virtual method can be reimplemented on a subclass.
getContext()
CuContext * QuNumericControlW::getContext () const
returns a pointer to the context
Returns
a pointer to the CuContext
onAnimationValueChanged
void QuNumericControlW::onAnimationValueChanged (const QVariant & v) slot
onUpdate()
void QuNumericControlW::onUpdate (const CuData & da)
configures the widget as soon as it is connected and records write errors.
Parameters
da CuData containing configuration options upon link creation or write operation results.
References perr, pinfo, qstoc, QuNumericW::setDecDigits(), QuNumericW::setIntDigits(), QuNumericW::setMaximum(), QuNumericW::setMinimum(), QuNumericW::setValue(), and target.
setTarget
void QuNumericControlW::setTarget (const QString & target) slot
Set the name of the target that will be executed.
Refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
References target.
target()
QString QuNumericControlW::target () const
returns the target name.
Returns
the target name, or an empty string if setTarget hasn't been called yet.
Refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
Property Documentation
target
QString QuNumericControlW::target read write
Referenced by onUpdate(), and setTarget().
The documentation for this class was generated from the following files:
qunumericcontrol_w.h
qunumericcontrol_w.cpp