cumbia-qtcontrols-ng: ScaleItem Class Reference
ScaleItem Class Reference
The QGraphicsObject that draws a plot scale on a PlotSceneWidget.
#include <scaleitem.h>
Public Types
enum { Type = UserType + 2 }
enum Orientation { Horizontal , Vertical }
enum Id {
xBottom , yLeft , xTop , yRight ,
User = 100
}
the id of the ScaleItem (kind of axis)
Public Slots
void setTickStepLen (double len)
void setAxisLabelsEnabled (bool en)
void setAxisLabelsRotation (double angle)
void setAxisLabelsFormat (const QString &fmt)
void setGridEnabled (bool en)
void setGridColor (const QColor &c)
void setAxisColor (const QColor &c)
void setUpperBound (double ub)
sets the axis maximum value (upper bound)
void setLowerBound (double lb)
sets the axis minimum value (lower bound)
void setLowerBoundDateTime (const QDateTime &t)
Sets the lower bound according to a given QDateTime timestamp.
void setUpperBoundDateTime (const QDateTime &t)
Sets the upper bound according to a given QDateTime timestamp.
void setAxisAutoscaleEnabled (bool en)
enables or disables the axis auto scaling
void setBounds (double lowerBound, double upperBound)
sets upper and lower bounds
bool setBoundsFromCurves ()
void setXlbAutoscaleMargin (double spanPercent)
When in auto scale mode, the autoscaleMargin property defines a margin to apply to the span. Factor between 0 and 1.
void setXubAutoscaleMargin (double spanPercent)
void setYlbAutoscaleMargin (double spanPercent)
void setYubAutoscaleMargin (double spanPercent)
void setAxisLabelDist (double d)
sets the distance between the backbone and the start of the label's text.
void setFont (const QFont &f)
void setAxisTitleFont (const QFont &fo)
void setAxisTitleColor (const QColor &co)
void setAxisTitle (const QString &ti)
void updateLabelsCache ()
void setVisible (bool visible)
Signals
void upperBoundChanged (double max)
this signal is emitted when the axis upper bound changes
void lowerBoundChanged (double min)
this signal is emitted when the axis lower bound changes
void autoscaleEnabledChanged (bool enabled)
this signal notifies that the auto scale property has changed
Public Member Functions
virtual int type () const
virtual ~ScaleItem ()
ScaleItem (Orientation o, QGraphicsPlotItem *parent, Id id)
Constructs a scale item with an Orientation, a reference to the PlotSceneWidget and an id aimed at identifying the axis.
void setOrientation (Orientation o)
Orientation orientation () const
Id axisId () const
double tickStepLen () const
double axisLabelsRotation () const
QString axisLabelsFormat () const
bool gridEnabled () const
bool axisLabelsEnabled () const
QColor gridColor () const
QColor axisColor () const
QRectF boundingRect () const
double upperBound () const
returns the upper bound (maximum value) of the scale
double lowerBound () const
returns the lower bound (minimum value) of the scale
QDateTime lowerBoundDateTime () const
returns the lower bound as a QDateTime object
QDateTime upperBoundDateTime () const
returns the upper bound as a QDateTime object
QDateTime doubleToDateTime (double d) const
bool axisAutoscaleEnabled () const
returns the value of the axisAutoscaleEnabled property
void adjustScaleBounds (double newMin, double newMax)
double axisLabelDist () const
defines the distance between the backbone and the start of the label's text
double xlbAutoscaleMargin () const
double xubAutoscaleMargin () const
double ylbAutoscaleMargin () const
double yubAutoscaleMargin () const
QFont font () const
QFont axisTitleFont () const
QColor axisTitleColor () const
QString axisTitle () const
virtual void fullVectorUpdate ()
void affectingBoundsPointsRemoved ()
virtual void plotRectChanged (const QRectF &newRect)
implementation of PlotChangeListener::plotRectChanged interface
virtual void plotAreaChanged (const QSizeF &area)
Empty body. We are not interested in area changes.
virtual void plotZoomLevelChanged (int level)
is called when the plot zoom level changes.
virtual void itemsAboutToBeDrawn ()
implementation of PlotChangeListener::sceneContentChanged interface
void installAxisChangeListener (AxisChangeListener *l)
Install an AxisChangeListener in order to be notified when axis bounds change or the auto scale property changes.
void removeAxisChangeListener (AxisChangeListener *l)
void installScaleLabelInterface (ScaleLabelInterface *iface)
Provide a custom label manager for the ScaleItem.
ScaleLabelInterface * scaleLabelInterface () const
returns the ScaleLabelInterface that was installed with installScaleLabelInterface, null otherwise.
void removeScaleLabelInterface ()
removes the custom scale label interface implementation.
QString label (double value) const
returns the label associated to the value passed as parameter, if a ScaleLabelInterface has been installed on the ScaleItem, the value itself otherwise.
double maxLabelWidth () const
QRectF plotArea () const
Returns the canvas rect, which is the rect where the curves can be drawn.
Public Member Functions inherited from PlotGeometryEventListener
PlotGeometryEventListener ()
virtual void plotRectChanged (const QRectF &newRect)=0
pure virtual method that needs to be reimplemented in order to be notified when the plot rect changes
virtual void plotAreaChanged (const QSizeF &area)=0
pure virtual method that needs to be reimplemented in order to be notified when the plot area changes.
virtual void plotZoomLevelChanged (int level)=0
Public Attributes
double plotAreaW
double scaledCanvasWidth
double plotAreaH
double scaledCanvasHeight
Protected Member Functions
void mNotifyBoundsChanged ()
void updateLabelsFormat (const QString &desiredFormat)
double updateStepLen ()
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
Properties
double tickStepLen
bool axisLabelsEnabled
bool gridEnabled
double axisLabelsRotation
QString axisLabelsFormat
QColor gridColor
QColor axisColor
QColor axisTitleColor
QString axisTitle
QFont axisTitleFont
double upperBound
double lowerBound
QDateTime lowerBoundDateTime
QDateTime upperBoundDateTime
bool axisAutoscaleEnabled
double axisLabelDist
QFont font
qreal zValue
Detailed Description
The QGraphicsObject that draws a plot scale on a PlotSceneWidget.
Description
The ScaleItem is a QGraphicsObject that draws and axis scale on a PlotSceneWidget. What a ScaleItem draws is:
a line for the backbone;
ticks on the backbone
labels on each tick, when there is enough space to draw the text.
Position of the axes
The axes are placed by PlotSceneWidget through the classes AxesManager and AxisCouple. Each AxisCouple in the PlotSceneWidget represents a couple of axis, one with Horizontal orientation and the other with Vertical orientation. The default positioning of the axes is done by default such as each the axes cross each other in the middle. If you want to change the reciprocal axes position, see PlotSceneWidget::setOriginPosPercentage PlotSceneWidget::setDefaultXAxisOriginPosPercentage and PlotSceneWidget::setDefaultYAxisOriginPosPercentage.
Relevant axis properties
tickStepLen the distance between two subsequent ticks, in scale coordinates. A tick step length of one on the x axis means one tick every increment of one on the x value If tickStepLen is set to -1, then the ticks distance is automatically chosen.
axisLabelsEnabled enables or disables the text labels on the axis.
gridEnabled shows or hides the grid on the plot
axisLabelsFormat the format of the number to display on the axis (it's printf() format)
upperBound sets the upper bound on the scale item. axisAutoscaleEnabled must be set to false
lowerBound sets the lower bound on the scale item. axisAutoscaleEnabled must be set to false
axisAutoscaleEnabled enables or disables auto scaling.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Id
enum ScaleItem::Id
the id of the ScaleItem (kind of axis)
PlotSceneWidget manages the two default axes for you, and gives them the xBottom and yLeft ids, respectively. If you need more axes, add them with the other available id or use another value of your choice.
Enumerator
xBottom
yLeft
xTop
yRight
User
Orientation
enum ScaleItem::Orientation
Enumerator
Horizontal
Vertical
Constructor & Destructor Documentation
~ScaleItem()
ScaleItem::~ScaleItem () virtual
ScaleItem()
ScaleItem::ScaleItem (Orientation o, QGraphicsPlotItem * parent, ScaleItem::Id id)
Constructs a scale item with an Orientation, a reference to the PlotSceneWidget and an id aimed at identifying the axis.
The PlotSceneWidget creates two ScaleItem objects for you, an x item and an y item. They are laid out so that they cross each other in the middle (see PlotSceneWidget::setOriginPosPercentage, PlotSceneWidget::setDefaultXAxisOriginPosPercentage and PlotSceneWidget::setDefaultYAxisOriginPosPercentage)
If you want to customize the scale labels, then subclass ScaleLabelInterface and provide a method named label in order to tell the ScaleItem what text to draw in correspondance to a specific value on the axis.
See also
ScaleLabelInterface
The ScaleItem is a QGraphicsObject which is added to the scene of the PlotSceneWidget.
The ScaleItem::Id is an enum with a bunch of default items. PlotSceneWidget manages the two default axes for you. If you want to add more axes, please have a look to the ScaleItem::Id enum and use one of the predefined values or add others by yourself.
References QGraphicsPlotItem::boundingRect(), plotAreaH, plotAreaW, updateStepLen(), and Vertical.
Member Function Documentation
adjustScaleBounds()
void ScaleItem::adjustScaleBounds (double newMin, double newMax)
References setBounds().
affectingBoundsPointsRemoved()
void ScaleItem::affectingBoundsPointsRemoved ()
References setBoundsFromCurves().
autoscaleEnabledChanged
void ScaleItem::autoscaleEnabledChanged (bool enabled) signal
this signal notifies that the auto scale property has changed
Parameters
enabled true the auto scale mode is enabled
enabled false the auto scale mode is disabled
See also
setAxisAutoscaleEnabled
axisAutoscaleEnabled
Referenced by setAxisAutoscaleEnabled().
axisAutoscaleEnabled()
bool ScaleItem::axisAutoscaleEnabled () const
returns the value of the axisAutoscaleEnabled property
Returns
true the axis scale is set according to the maximum value of the curves attached to the axis itself.
false the axis range is set according to upperBound and lowerBound properties.
See also
setUpperBound
setLowerBound
upperBound
lowerBound
setAxisAutoscaleEnabled
axisColor()
QColor ScaleItem::axisColor () const
axisId()
ScaleItem::Id ScaleItem::axisId () const
Referenced by AxesManager::getAssociatedAxis(), AxesManager::getAxis(), AxesManager::getOriginPosPercentage(), paint(), updateLabelsCache(), QGraphicsZoomer::xAxis(), and QGraphicsZoomer::yAxis().
axisLabelDist()
double ScaleItem::axisLabelDist () const
defines the distance between the backbone and the start of the label's text
Returns
the distance, in pixels, between the backbone of the axis and the start of text.
The default value is 5
See also
setAxisLabelDist
axisLabelsEnabled()
bool ScaleItem::axisLabelsEnabled () const
axisLabelsFormat()
QString ScaleItem::axisLabelsFormat () const
axisLabelsRotation()
double ScaleItem::axisLabelsRotation () const
axisTitle()
QString ScaleItem::axisTitle () const
axisTitleColor()
QColor ScaleItem::axisTitleColor () const
axisTitleFont()
QFont ScaleItem::axisTitleFont () const
boundingRect()
QRectF ScaleItem::boundingRect () const
References boundingRect().
Referenced by boundingRect().
doubleToDateTime()
QDateTime ScaleItem::doubleToDateTime (double d) const
Referenced by lowerBoundDateTime(), and upperBoundDateTime().
font()
QFont ScaleItem::font () const
fullVectorUpdate()
void ScaleItem::fullVectorUpdate () virtual
gridColor()
QColor ScaleItem::gridColor () const
gridEnabled()
bool ScaleItem::gridEnabled () const
installAxisChangeListener()
void ScaleItem::installAxisChangeListener (AxisChangeListener * l)
Install an AxisChangeListener in order to be notified when axis bounds change or the auto scale property changes.
Parameters
l an implementation of the AxisChangeListener interface
See also
AxisChangeListener
References AxisChangeListener::axisAutoscaleChanged(), Horizontal, AxisChangeListener::labelsFormatChanged(), AxisChangeListener::plotAreaChanged(), AxisChangeListener::tickStepLenChanged(), AxisChangeListener::xAxisBoundsChanged(), and AxisChangeListener::yAxisBoundsChanged().
Referenced by QGraphicsPlotItem::addCurve(), QGraphicsPlotItem::addLineCurve(), and QGraphicsZoomer::addScale().
installScaleLabelInterface()
void ScaleItem::installScaleLabelInterface (ScaleLabelInterface * iface)
Provide a custom label manager for the ScaleItem.
If a ScaleLabelInterface implementation is provided, then the labels text will be obtained by ScaleLabelInterface::label method.
See also
ScaleLabelInterface
Parameters
iface an object implementing the ScaleLabelInterface interface
The ScaleItem class does not take ownership of the scale label interface. This means that removeScaleLabelInterface will not delete the installed interface and that subsequent calls to installScaleLabelInterface will not delete previously installed scale label interfaces.
References updateLabelsCache().
itemsAboutToBeDrawn()
void ScaleItem::itemsAboutToBeDrawn () virtual
implementation of PlotChangeListener::sceneContentChanged interface
label()
QString ScaleItem::label (double value) const
returns the label associated to the value passed as parameter, if a ScaleLabelInterface has been installed on the ScaleItem, the value itself otherwise.
Parameters
value the value on the ScaleItem whose label you want to retrieve
Returns
the label associated to the value value.
See also
installScaleLabelInterface
ScaleLabelInterface
Referenced by MarkerItem::paint().
lowerBound()
double ScaleItem::lowerBound () const
returns the lower bound (minimum value) of the scale
Axis auto scale must be disabled otherwise this call will have no effect.
Returns
the lower bound of the ScaleItem
See also
setUpperBound
setLowerBound
upperBound
setAxisAutoscaleEnabled
lowerBoundChanged
void ScaleItem::lowerBoundChanged (double min) signal
this signal is emitted when the axis lower bound changes
Parameters
max the new axis lower bound
See also
upperBoundChanged
Referenced by setBounds(), setBoundsFromCurves(), and setLowerBound().
lowerBoundDateTime()
QDateTime ScaleItem::lowerBoundDateTime () const
returns the lower bound as a QDateTime object
Returns
the lower bound as a QDateTime object
Conversion
The decimal part of the double value representing the axis bound is used to set the milliseconds, the integer part is interpreted as a unix timestamp, i.e. the number of seconds that have passed since 1970-01-01T00:00:00, Coordinated Universal Time.
See also
setUpperBoundDateTime
setLowerBoundDateTime
upperBoundDateTime
TimeScaleLabel
References doubleToDateTime().
maxLabelWidth()
double ScaleItem::maxLabelWidth () const
Referenced by paint().
mNotifyBoundsChanged()
void ScaleItem::mNotifyBoundsChanged () protected
References Horizontal, AxisChangeListener::xAxisBoundsChanged(), and AxisChangeListener::yAxisBoundsChanged().
Referenced by setBounds(), setLowerBound(), and setUpperBound().
orientation()
ScaleItem::Orientation ScaleItem::orientation () const
Referenced by QGraphicsPlotItem::addAxis(), AxesManager::getAxes(), QGraphicsPlotItem::invTransform(), QGraphicsPlotItem::originPosPercentage(), QGraphicsPlotItem::setOriginPosPercentage(), QGraphicsPlotItem::transform(), and QGraphicsZoomer::zoom().
paint()
void ScaleItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0) protected
DEBUG STUFF
References QGraphicsPlotItem::associatedAxis(), QGraphicsPlotItem::associatedOriginPosPercentage(), axisId(), QGraphicsPlotItem::boundingRect(), Horizontal, lowerBound, maxLabelWidth(), perr, AxisChangeListener::plotAreaChanged(), plotAreaH, plotAreaW, qstoc, tickStepLen, updateLabelsFormat(), upperBound, and Vertical.
plotArea()
QRectF ScaleItem::plotArea () const
Returns the canvas rect, which is the rect where the curves can be drawn.
This rect does not coincide with the plot rect if the axis labels do not fit into the canvas.
Referenced by QGraphicsPlotItem::transform().
plotAreaChanged()
void ScaleItem::plotAreaChanged (const QSizeF & area) virtual
Empty body. We are not interested in area changes.
The area passed as parameter takes into account the scaling factor of the view (not needed here).
Implements PlotGeometryEventListener.
References updateLabelsCache(), and updateStepLen().
plotRectChanged()
void ScaleItem::plotRectChanged (const QRectF & newRect) virtual
implementation of PlotChangeListener::plotRectChanged interface
Implements PlotGeometryEventListener.
plotZoomLevelChanged()
void ScaleItem::plotZoomLevelChanged (int level) virtual
is called when the plot zoom level changes.
This method is called when the plot zoom level changes.
Parameters
level the level of the zoom
Note
Together with axes bound change, it is the third case in which you need to calculate the tick step length again.
Implements PlotGeometryEventListener.
References updateLabelsCache(), and updateStepLen().
removeAxisChangeListener()
void ScaleItem::removeAxisChangeListener (AxisChangeListener * l)
Referenced by QGraphicsPlotItem::curveAboutToBeDestroyed(), QGraphicsZoomer::removeScale(), and QGraphicsZoomer::~QGraphicsZoomer().
removeScaleLabelInterface()
void ScaleItem::removeScaleLabelInterface ()
removes the custom scale label interface implementation.
If this method is called, then the ScaleItem labels text will simply display the values of the x data.
scaleLabelInterface()
ScaleLabelInterface * ScaleItem::scaleLabelInterface () const
returns the ScaleLabelInterface that was installed with installScaleLabelInterface, null otherwise.
Returns
the installed ScaleLabelInterface or NULL if it was not installed.
See also
installScaleLabelInterface
Referenced by QGraphicsPlotItem::saveData().
setAxisAutoscaleEnabled
void ScaleItem::setAxisAutoscaleEnabled (bool en) slot
enables or disables the axis auto scaling
See also
setUpperBound
setLowerBound
upperBound
lowerBound
axisAutoscaleEnabled
References autoscaleEnabledChanged(), and AxisChangeListener::axisAutoscaleChanged().
Referenced by QGraphicsPlotItem::setXAxisAutoscaleEnabled(), and QGraphicsPlotItem::setYAxisAutoscaleEnabled().
setAxisColor
void ScaleItem::setAxisColor (const QColor & c) slot
setAxisLabelDist
void ScaleItem::setAxisLabelDist (double dv) slot
sets the distance between the backbone and the start of the label's text.
Parameters
d the distance, in scene coordinates, between the backbone and the start of text of each label.
setAxisLabelsEnabled
void ScaleItem::setAxisLabelsEnabled (bool en) slot
References updateLabelsCache().
setAxisLabelsFormat
void ScaleItem::setAxisLabelsFormat (const QString & fmt) slot
References updateLabelsCache(), and updateLabelsFormat().
setAxisLabelsRotation
void ScaleItem::setAxisLabelsRotation (double angle) slot
setAxisTitle
void ScaleItem::setAxisTitle (const QString & ti) slot
setAxisTitleColor
void ScaleItem::setAxisTitleColor (const QColor & co) slot
setAxisTitleFont
void ScaleItem::setAxisTitleFont (const QFont & fo) slot
setBounds
void ScaleItem::setBounds (double lowerBound, double upperBound) slot
sets upper and lower bounds
Axis auto scale must be disabled otherwise this call will have no effect.
See also
setUpperBound
setLowerBound
Note
recalculates the actual tick step len if not set by the user.
References lowerBound, lowerBoundChanged(), mNotifyBoundsChanged(), perr, updateLabelsCache(), updateLabelsFormat(), updateStepLen(), upperBound, and upperBoundChanged().
Referenced by adjustScaleBounds(), QGraphicsZoomer::unzoom(), and QGraphicsZoomer::zoom().
setBoundsFromCurves
bool ScaleItem::setBoundsFromCurves () slot
References SceneCurve::curveItem(), SceneCurve::data(), Horizontal, lowerBoundChanged(), perr, updateLabelsCache(), updateLabelsFormat(), updateStepLen(), upperBoundChanged(), AxisChangeListener::xAxisBoundsChanged(), Data::xMax, Data::xMin, AxisChangeListener::yAxisBoundsChanged(), Data::yMax, and Data::yMin.
Referenced by affectingBoundsPointsRemoved().
setFont
void ScaleItem::setFont (const QFont & f) slot
References updateLabelsCache().
setGridColor
void ScaleItem::setGridColor (const QColor & c) slot
setGridEnabled
void ScaleItem::setGridEnabled (bool en) slot
setLowerBound
void ScaleItem::setLowerBound (double lb) slot
sets the axis minimum value (lower bound)
Parameters
lb the value of the lower bound.
axisAutoscaleEnabled property must be set to false.
See also
setUpperBound
upperBound
lowerBound
setAxisAutoscaleEnabled
References lowerBoundChanged(), mNotifyBoundsChanged(), perr, updateLabelsCache(), updateLabelsFormat(), updateStepLen(), and upperBound.
Referenced by setLowerBoundDateTime(), QGraphicsPlotItem::setXAxisLowerBound(), and QGraphicsPlotItem::setYAxisLowerBound().
setLowerBoundDateTime
void ScaleItem::setLowerBoundDateTime (const QDateTime & t) slot
Sets the lower bound according to a given QDateTime timestamp.
Sets the lower bound according to a given QDateTime timestamp.
Parameters
t a QDateTime representing the lower bound of the scale.
Note
the QDateTime is converted into a double with the millisecond precision: t.toTime_t() + 0.001 * t.time().msec()
This method is useful when your scale is a time scale.
See also
TimeScaleLabel
setUpperBoundDateTime
lowerBoundDateTime
References setLowerBound().
setOrientation()
void ScaleItem::setOrientation (Orientation o)
setTickStepLen
void ScaleItem::setTickStepLen (double len) slot
References AxisChangeListener::tickStepLenChanged(), updateLabelsCache(), and updateStepLen().
setUpperBound
void ScaleItem::setUpperBound (double ub) slot
sets the axis maximum value (upper bound)
Parameters
ub the value of the upper bound.
axisAutoscaleEnabled property must be set to false.
See also
setLowerBound
upperBound
setAxisAutoscaleEnabled
References mNotifyBoundsChanged(), perr, updateLabelsCache(), updateLabelsFormat(), updateStepLen(), and upperBoundChanged().
Referenced by setUpperBoundDateTime(), QGraphicsPlotItem::setXAxisUpperBound(), and QGraphicsPlotItem::setYAxisUpperBound().
setUpperBoundDateTime
void ScaleItem::setUpperBoundDateTime (const QDateTime & t) slot
Sets the upper bound according to a given QDateTime timestamp.
Sets the upper bound according to a given QDateTime timestamp.
Note
This method is useful when your scale is a time scale.
See also
setLowerBoundDateTime
lowerBoundDateTime
TimeScaleLabel
References setUpperBound().
setVisible
void ScaleItem::setVisible (bool visible) slot
Referenced by QGraphicsPlotItem::setXScaleEnabled(), and QGraphicsPlotItem::setYScaleEnabled().
setXlbAutoscaleMargin
void ScaleItem::setXlbAutoscaleMargin (double spanPercent) slot
When in auto scale mode, the autoscaleMargin property defines a margin to apply to the span. Factor between 0 and 1.
setXubAutoscaleMargin
void ScaleItem::setXubAutoscaleMargin (double spanPercent) slot
setYlbAutoscaleMargin
void ScaleItem::setYlbAutoscaleMargin (double spanPercent) slot
setYubAutoscaleMargin
void ScaleItem::setYubAutoscaleMargin (double spanPercent) slot
tickStepLen()
double ScaleItem::tickStepLen () const
type()
virtual int ScaleItem::type () const inline virtual
References Type.
updateLabelsCache
void ScaleItem::updateLabelsCache () slot
References axisId(), Horizontal, and qstoc.
Referenced by installScaleLabelInterface(), plotAreaChanged(), plotZoomLevelChanged(), setAxisLabelsEnabled(), setAxisLabelsFormat(), setBounds(), setBoundsFromCurves(), setFont(), setLowerBound(), QGraphicsPlotItem::setOriginPosPercentage(), setTickStepLen(), and setUpperBound().
updateLabelsFormat()
void ScaleItem::updateLabelsFormat (const QString & desiredFormat) protected
References AxisChangeListener::labelsFormatChanged().
Referenced by paint(), setAxisLabelsFormat(), setBounds(), setBoundsFromCurves(), setLowerBound(), and setUpperBound().
updateStepLen()
double ScaleItem::updateStepLen () protected
References AxisChangeListener::tickStepLenChanged().
Referenced by plotAreaChanged(), plotZoomLevelChanged(), ScaleItem(), setBounds(), setBoundsFromCurves(), setLowerBound(), setTickStepLen(), and setUpperBound().
upperBound()
double ScaleItem::upperBound () const
returns the upper bound (maximum value) of the scale
Axis auto scale must be disabled otherwise this call will have no effect.
Returns
the upper bound of the ScaleItem
See also
setUpperBound
setLowerBound
lowerBound
setAxisAutoscaleEnabled
upperBoundChanged
void ScaleItem::upperBoundChanged (double max) signal
this signal is emitted when the axis upper bound changes
Parameters
max the new axis upper bound
See also
lowerBoundChanged
Referenced by setBounds(), setBoundsFromCurves(), and setUpperBound().
upperBoundDateTime()
QDateTime ScaleItem::upperBoundDateTime () const
returns the upper bound as a QDateTime object
Returns
the upper bound as a QDateTime object
See also
lowerBoundDateTime
References doubleToDateTime().
xlbAutoscaleMargin()
double ScaleItem::xlbAutoscaleMargin () const
xubAutoscaleMargin()
double ScaleItem::xubAutoscaleMargin () const
ylbAutoscaleMargin()
double ScaleItem::ylbAutoscaleMargin () const
yubAutoscaleMargin()
double ScaleItem::yubAutoscaleMargin () const
Member Data Documentation
plotAreaH
double ScaleItem::plotAreaH
Referenced by QGraphicsPlotItem::invTransform(), paint(), ScaleItem(), and QGraphicsPlotItem::transform().
plotAreaW
double ScaleItem::plotAreaW
Referenced by QGraphicsPlotItem::invTransform(), paint(), ScaleItem(), and QGraphicsPlotItem::transform().
scaledCanvasHeight
double ScaleItem::scaledCanvasHeight
scaledCanvasWidth
double ScaleItem::scaledCanvasWidth
Property Documentation
axisAutoscaleEnabled
bool ScaleItem::axisAutoscaleEnabled read write
Referenced by QGraphicsPlotItem::xAxisAutoscaleEnabled(), and QGraphicsPlotItem::yAxisAutoscaleEnabled().
axisColor
QColor ScaleItem::axisColor read write
axisLabelDist
double ScaleItem::axisLabelDist read write
axisLabelsEnabled
bool ScaleItem::axisLabelsEnabled read write
axisLabelsFormat
QString ScaleItem::axisLabelsFormat read write
axisLabelsRotation
double ScaleItem::axisLabelsRotation read write
axisTitle
QString ScaleItem::axisTitle read write
axisTitleColor
QColor ScaleItem::axisTitleColor read write
axisTitleFont
QFont ScaleItem::axisTitleFont read write
font
QFont ScaleItem::font read write
gridColor
QColor ScaleItem::gridColor read write
gridEnabled
bool ScaleItem::gridEnabled read write
lowerBound
double ScaleItem::lowerBound read write
Referenced by QGraphicsPlotItem::invTransform(), CurveItem::itemAdded(), paint(), setBounds(), QGraphicsPlotItem::transform(), QGraphicsPlotItem::xAxisLowerBound(), QGraphicsPlotItem::yAxisLowerBound(), and QGraphicsZoomer::zoom().
lowerBoundDateTime
QDateTime ScaleItem::lowerBoundDateTime read write
tickStepLen
double ScaleItem::tickStepLen read write
Referenced by paint().
upperBound
double ScaleItem::upperBound read write
Referenced by QGraphicsPlotItem::invTransform(), CurveItem::itemAdded(), paint(), setBounds(), setLowerBound(), QGraphicsPlotItem::transform(), QGraphicsPlotItem::xAxisUpperBound(), QGraphicsPlotItem::yAxisUpperBound(), and QGraphicsZoomer::zoom().
upperBoundDateTime
QDateTime ScaleItem::upperBoundDateTime read write
zValue
qreal ScaleItem::zValue read write
The documentation for this class was generated from the following files:
scaleitem.h
scaleitem.cpp