cumbia-qtcontrols-ng: EditSourceDialog Class Reference
EditSourceDialog Class Reference
#include <editsourcedialog.h>
Public Member Functions
EditSourceDialog (QWidget *=nullptr)
virtual ~EditSourceDialog ()
QString source () const
void setSource (const QString &s)
void accept ()
bool checkSource ()
QString message ()
EditSourceDialog (QWidget *=nullptr)
virtual ~EditSourceDialog ()
QString source () const
void setSource (const QString &s)
void accept ()
bool checkSource ()
QString message ()
Public Attributes
Ui::EditSourceDialog ui
Protected Slots
void addSrcTab ()
void addSrcTab ()
Constructor & Destructor Documentation
EditSourceDialog() [1/2]
EditSourceDialog::EditSourceDialog (QWidget * parent = nullptr)
References addSrcTab(), and ui.
~EditSourceDialog() [1/2]
EditSourceDialog::~EditSourceDialog () virtual
EditSourceDialog() [2/2]
EditSourceDialog::EditSourceDialog (QWidget * = nullptr)
~EditSourceDialog() [2/2]
virtual EditSourceDialog::~EditSourceDialog () virtual
Member Function Documentation
accept() [1/2]
void EditSourceDialog::accept ()
References checkSource().
accept() [2/2]
void EditSourceDialog::accept ()
addSrcTab [1/2]
void EditSourceDialog::addSrcTab () protected slot
References ui.
Referenced by EditSourceDialog().
addSrcTab [2/2]
void EditSourceDialog::addSrcTab () protected slot
checkSource() [1/2]
bool EditSourceDialog::checkSource ()
References EditSourceWidget::checkSource().
Referenced by accept().
checkSource() [2/2]
bool EditSourceDialog::checkSource ()
message() [1/2]
QString EditSourceDialog::message ()
message() [2/2]
QString EditSourceDialog::message ()
setSource() [1/2]
void EditSourceDialog::setSource (const QString & s)
setSource() [2/2]
void EditSourceDialog::setSource (const QString & s)
source() [1/2]
QString EditSourceDialog::source () const
source() [2/2]
QString EditSourceDialog::source () const
Member Data Documentation
ui
Ui::EditSourceDialog EditSourceDialog::ui
Referenced by addSrcTab(), and EditSourceDialog().
The documentation for this class was generated from the following files:
base/cumbia-qtcontrols-ng-base-designer/forms/editsourcedialog.h
controls/cumbia-qtcontrols-ng-controls-designer/forms/editsourcedialog.h
base/cumbia-qtcontrols-ng-base-designer/forms/cumbia-image-plugin-designer.cpp
controls/cumbia-qtcontrols-ng-controls-designer/forms/cumbia-image-plugin-designer.cpp