cumbia-qtcontrols-ng: QGraphicsPlotItem Class Reference
QGraphicsPlotItem Class Reference
The main class that contains the plot canvas.
#include <qgraphicsplotitem.h>
Public Types
enum Axis {
xBottom , yLeft , xTop , yRight ,
User = 100
}
Public Slots
void resize (const QSizeF &s)
void setGeometry (const QRectF &r)
void setXScaleEnabled (bool en)
void setYScaleEnabled (bool en)
void setMouseZoomEnabled (bool en)
Enables the zoom with the mouse, when the Ctrl key and the left mouse button are pressed.
void setManualUpdate (bool manual)
This is an important optimization that acts on the QGraphicsView::ViewportUpdateMode that comes into relevance when you have several items that must be fastly drawn.
void setRefreshPeriod (int period)
sets the refresh period of the internal timer used to refresh the scene when manualSceneUpdate is turned on.
void executePropertyDialog ()
virtual void appendData (const QString &curveName, double x, double y)
virtual void appendData (const QString &curveName, const QVector< double > &xData, const QVector< double > &yData)
virtual void setData (const QString &curveName, const QVector< double > &xData, const QVector< double > &yData)
virtual void setData (const QString &curveName, const QVector< double > &yData)
void setOriginPosPercentage (ScaleItem *scaleIt, double percent)
sets the position of the origin of the given scale item to the specified percent value, in percentage terms from 0 to 1.0
void setDefaultXAxisOriginPosPercentage (double percent)
Changes the position of the default x axis.
void setDefaultYAxisOriginPosPercentage (double percent)
Changes the position of the default y axis.
void setLegendVisible (bool visible)
void setXAxisLowerBound (double xlb)
Shortcut to access the x axis and set the bound.
void setYAxisLowerBound (double ylb)
Shortcut to access the y axis and set the bound.
void setXAxisUpperBound (double xub)
Shortcut to access the x axis and set the bound.
void setYAxisUpperBound (double yub)
Shortcut to access the y axis and set the bound.
void setXAxisAutoscaleEnabled (bool en)
Shortcut to enable/disable the autoscale on the x axis.
void setYAxisAutoscaleEnabled (bool en)
Shortcut to enable/disable the autoscale on the x axis.
void setBackgroundColor (const QColor &)
void saveData ()
virtual QMenu * createContextMenu ()
QRectF boundingRect () const
Signals
void clicked (const QPointF &pos)
the plot was clicked at the position pos
void plotRectChanged (const QRectF &newRect)
The plot rectangle has changed.
void plotAreaChanged (const QSizeF &newSize)
notifies that the plot area has changed
void curveAboutToBeRemoved (SceneCurve *c)
this signal is emitted when a curve is removed from the plot
void curveAdded (SceneCurve *curve)
This signal notifies that the curve has been added to the plot.
Public Member Functions
QGraphicsPlotItem (QGraphicsItem *parent=nullptr)
PlotSceneWidget is a QGraphicsView with a QGraphicsScene where QGraphicsItem items can be placed and displayed. In particular, PlotSceneWidget is a plot where curves can be drawn.
QGraphicsPlotItem (bool initDefaultAxes, QGraphicsItem *parent=nullptr)
virtual ~QGraphicsPlotItem ()
bool xScaleEnabled () const
bool yScaleEnabled () const
bool mouseZoomEnabled () const
returns the mouse zoom enable state
bool smoothPixmapTransform () const
bool legendVisible () const
virtual void boundsChanged ()
void installPlotGeometryChangeListener (PlotGeometryEventListener *l)
void removePlotGeometryChangeListener (PlotGeometryEventListener *l)
void installMouseEventListener (MouseEventListener *l)
void removeMouseEventListener (MouseEventListener *l)
QColor backgroundColor () const
QList< Point * > getPoints () const
ScaleItem * xScaleItem () const
shortcut to retrieve the x scale item (ScaleItem::xBottom) which is always created by default.
ScaleItem * yScaleItem () const
shortcut to retrieve the y scale item (ScaleItem::yLeft) which is always created by default.
ScaleItem * scaleItem (ScaleItem::Id id) const
returns the ScaleItem associated to the argument.
ScaleItem * associatedAxis (ScaleItem::Id otherAxisId) const
QPair< double, double > associatedOriginPosPercentage (ScaleItem::Id xAxisId, ScaleItem::Id yAxisId, bool *ok) const
void addConfigurableObjects (const QString &title, QObject *object)
add an object which is configurable through its Qt properties.
void removeConfigurableObjects (const QString &title)
removes an object which was previously added with addConfigurableObjects with the given title.
void loadConfigurationProperties ()
QPointF invTransform (const QPointF &pSceneCoord)
transforms a QPointF in scene coordinates into a QPointF containing the x and y values in the x and y axis scale coordinates.
double invTransform (const double xCoord, ScaleItem *scaleItem) const
transforms a double in scene coordinates into a double in scaleItem coordinates
double transform (const double x, ScaleItem *scaleItem) const
transforms a value on the scaleItem axis in axis coordinates into a value in scene coordinates inside the plot rect.
QPointF invTransform (const QPointF &pSceneCoord, ScaleItem *xScaleItem, ScaleItem *yScaleItem) const
void addCurve (SceneCurve *curve)
SceneCurve * addCurve (const QString &name)
Creates a new curve with the given name and automatically associates it to the x bottom axis and y left axis.
SceneCurve * addCurve (const QString &name, ScaleItem *xScaleItem, ScaleItem *yScaleItem)
Creates a new curve with the given name and attachs the curve to the specified x and y ScaleItems (axes).
SceneCurve * findCurve (const QString &name)
finds the curve with the provided name
QList< SceneCurve * > getCurves () const
returns a list of all curves belonging to this plot
SceneCurve * addLineCurve (const QString &name, ScaleItem *xScaleItem=NULL, ScaleItem *yScaleItem=NULL)
adds and configures a curve with a LinePainter
void curveAboutToBeDestroyed (const QString &name, bool deleteCurve=true)
QList< SceneCurve * > curvesForAxes (ScaleItem::Id axisId, ScaleItem::Orientation orientation) const
returns the list of curves that are attached to the provided axisId with Orientation orientation
AxesManager * axesManager () const
returns the reference to the AxesManager.
QRectF plotRect () const
double originPosPercentage (ScaleItem *scaleIt) const
returns the origin position (in percentage between 0.0 and 1.0) of the scale item passed as parameter
double defaultXAxisOriginPosPercentage () const
returns the origin position (in percentage between 0.0 and 1.0) of the default x scale item (the one that the PlotSceneWidget always creates automatically)
double defaultYAxisOriginPosPercentage () const
returns the origin position (in percentage between 0.0 and 1.0) of the default y scale item (the one that the PlotSceneWidget always creates automatically)
double xAxisLowerBound () const
shortcut to get the axis bound from the xScaleItem()
double yAxisLowerBound () const
shortcut to get the axis bound from the yScaleItem()
double xAxisUpperBound () const
shortcut to get the axis bound from the xScaleItem()
double yAxisUpperBound () const
shortcut to get the axis bound from the yScaleItem()
bool xAxisAutoscaleEnabled () const
shortcut to get the axis autoscale mode from the xScaleItem()
bool yAxisAutoscaleEnabled () const
shortcut to get the axis autoscale mode from the yScaleItem()
int refreshPeriod () const
returns the refresh period of the internal timer used to refresh the scene when manualSceneUpdate is turned on.
QList< SceneCurve * > getClosest (QPointF &closestPos, int *closestIndex, const QPointF &viewPos)
retrieve the list of curves that are closest to the viewPos point in view coordinates. The closestPos point is the point, in scene coordinates, closest to the viewPos and belonging to the closest curves. The closestIndex is the x axis index coordinate of the closest point.
bool inZoom () const
returns the zoom state
int zoomLevel () const
returns the zoom level of the zoomer.
QGraphicsZoomer * zoomer () const
LegendItem * legendItem () const
ScaleItem * addAxis (ScaleItem::Orientation o, ScaleItem::Id id, ScaleItem *associatedAxis)
void removeAxis (ScaleItem::Id id)
void clearAxes (bool all=false, ScaleItem::Orientation o=ScaleItem::Vertical)
Removes the axes from the plot.
void clear ()
Public Member Functions inherited from XYPlotInterface
XYPlotInterface ()
virtual void appendData (const QString &curveName, double x, double y)=0
virtual void setData (const QString &curveName, const QVector< double > &xData, const QVector< double > &yData)=0
virtual void setData (const QString &curveName, const QVector< double > &yData)=0
Protected Slots
void curveAboutToBeDestroyed (QObject *crv)
this is a protected slot connected to the destroyed() signal of a SceneCurve
void removeAxis (QObject *axis)
Protected Member Functions
QVariant itemChange (QGraphicsItem::GraphicsItemChange change, const QVariant &value)
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *)
void mSwitchAxesCurvesForeground ()
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr)
void update (const QRectF &area=QRectF())
Properties
bool xScaleEnabled
bool yScaleEnabled
bool mouseZoomEnabled
int refreshPeriod
double defaultXAxisOriginPosPercentage
double defaultYAxisOriginPosPercentage
bool legendVisible
QColor backgroundColor
Detailed Description
The main class that contains the plot canvas.
This library can draw curves on a plot canvas. Each curve is represented by a SceneCurve. A SceneCurve contains the data of the curve. The SceneCurve is not responsible for drawing its shape. Each SceneCurve must be given a name and added to the plot by means of QGraphicsPlotItem::addCurve
The painting takes place by a CurveItem object constructed by passing a SceneCurve to it and by an implementation of an ItemPainterInterface which must be installed on a CurveItem.
The ScaleItem class represents an axis scale. More than a couple of axes may be added to the plot. AxesManager class is responsible of coupling and managing the axes.
The TargetItem item is a QGraphicsObject that can be moved over the plot and it is aimed at realizing writers.
Readers that want to draw curves on the plot have to conform to the XYPlotInterface interface that the QGraphicsPlotItem implements.
In the examples directory you will find some examples of the usage of the library.
See also
QGraphicsPlotItem
SceneCurve
CurveItem
ItemPainterInterface
LinePainter
DotsPainter
ScaleItem
Examples
Scalar plot
see directory examples/scalar
Spectrum plot
see directory examples/spectrum/
Aging circles
see directory examples/agingcircles
Using external scales
External scales can be used and they can be useful when the plot is zoomed and the plot internal axes fall out of the zoom area. You can find an example in the directory examples/externalscales
See also
ExternalScaleWidget
Properties and settings
Each QObject (in particular QGraphicsObject for the items in a plot) can export its relevant properties through a set of Q_PROPERTY declarations. These properties are then taken into account at runtime and the most important types of properties can be modified and saved. Each object will display its properties under a page of a tab widget. To register QObject's properties, the object must have an objectName and you must provide a settings key through the setSettingsKey method call, passing a string as a key for the properties of your objects to be saved by the QSettings class. Normally, you want to pass the application name as settings key.
Note
Since version 2.2.2, Qt dynamic properties directly set on QObjects with setProperty are taken into account and made available by the configuration dialog.
Dynamic properties starting with two underscores "__" are reserved and do not have to be used.
Since dynamic properties are expected to be application specific, their names are put in evidence by means of a bold font in the configuration dialog.
graphicsPlot->setSettingsKey(qApp->applicationName());
Each configurable object must then be registered with the addConfigurableObjects method call, passing the name of the tab in the tab widget for the object and a reference to the object itself.
graphicsPlot->addConfigurableObjects(curveItem->name() + " Properties", curveItem);
Position of the axes
The axes are placed by QGraphicsPlotItem through the classes AxesManager and AxisCouple. Each AxisCouple in the QGraphicsPlotItem represents a couple of axis, one with Horizontal orientation and the other with Vertical orientation. The default positioning of the axes is done by default such as each the axes cross each other in the middle. If you want to change the reciprocal axes position, see QGraphicsPlotItem::setOriginPosPercentage QGraphicsPlotItem::setDefaultXAxisOriginPosPercentage and QGraphicsPlotItem::setDefaultYAxisOriginPosPercentage.
// change the position of the axis
graphicsPlot->setDefaultXAxisOriginPosPercentage(0.0);
graphicsPlot->setDefaultYAxisOriginPosPercentage(0.1);
The code above produces the effect of placing the scales as in the scalartime example in the examples folder. Here you can see a screenshot of the scalartime example
In the scalartime example, the time labels in the x axis have been realized by installing a TimeScaleLabel on the x axis:
TimeScaleLabel *timeScaleLabel = new TimeScaleLabel();
graphicsPlot->xScaleItem()->installScaleLabelInterface(timeScaleLabel);
See also
TimeScaleLabel
installScaleLabelInterface
ScaleLabelInterface
To customize x or y scale labels, have a look to ScaleLabelInterface. You must subclass that interface and provide a ScaleLabelInterface::label method implementation.
Implementation notes
PlotGeometryEventListener and MouseEventListener interfaces can benefit from QGraphicsPlotItem notifications when the geometry of the plot changes (see PlotGeometryEventListener) or the mouse is clicked/moved/pressed/released on a certain point (see MouseEventListener). installMouseEventListener and installPlotGeometryChangeListener methods can be used by any class implementing the MouseEventListener and PlotGeometryEventListener interfaces in order to register for the corresponding events.
Other relevant changes taking place in the QGraphicsPlotItem are notified by means of Qt signals. For example, signals are emitted when a new curve is added or removed or an axis is removed. Appropriate signals are also emitted when the area of the plot changes (taking into account the currently applied transform matrix) and when the plot rect changes.
Member Enumeration Documentation
Axis
enum QGraphicsPlotItem::Axis
Enumerator
xBottom
yLeft
xTop
yRight
User
Constructor & Destructor Documentation
QGraphicsPlotItem() [1/2]
QGraphicsPlotItem::QGraphicsPlotItem (QGraphicsItem * parent = nullptr) explicit
PlotSceneWidget is a QGraphicsView with a QGraphicsScene where QGraphicsItem items can be placed and displayed. In particular, PlotSceneWidget is a plot where curves can be drawn.
PlotSceneWidget
PlotSceneWidget is a QGraphicsView with a QGraphicsScene where QGraphicsItem items can be placed and displayed. In particular, PlotSceneWidget is a plot where curves can be drawn.
Axes
A PlotSceneWidget has by default a couple of axes, the x and y axes, and their origin is by default in the center of the scene. If you want to change the axes position, see
PlotSceneWidget::setOriginPosPercentage
PlotSceneWidget::setDefaultXAxisOriginPosPercentage and
PlotSceneWidget::setDefaultYAxisOriginPosPercentage.
Reducing the plot area inside the scene.
It is possible to reduce the area occupied by the plot by means of the plotAreaPercentageWidth, plotAreaPercentageHeight, plotAreaTopLeftXPercentage, plotAreaTopLeftYPercentage properties.
Curves
Each curve is represented by a SceneCurve. A SceneCurve contains the data of the curve. The SceneCurve is not responsible for drawing itself. Each SceneCurve must be given a name and added to the plot by means of PlotSceneWidget::addCurve
The painting takes place by a CurveItem object instantiated by passing a SceneCurve to its constructor and by an implementation of an ItemPainterInterface which must be installed on a CurveItem. Once a CurveItem is constructed with a SceneCurve, the SceneCurve takes the ownership of the CurveItem, destroying it when the curve is destroyed. Once an ItemPainterInterface implementation instance is installed on a CurveItem, the CurveItem takes the ownership of the item painter destroying it on CurveItem destruction.
LinePainter is an example of an ItemPainterInterface implementation. DotsPainter is another example.
Example. Adding a curve to a PlotSceneWidget
SceneCurve *curve = myPlotSceneWidget->addCurve("Curve Name");
//
// if you want no more than bufsize points on the curve
int bufsize = 1000;
curve->setBufferSize(bufsize);
// Create the effective curve painter!
// Just pass the curve in the constructor
// The SceneCurve curve takes the ownership of curveItem, i.e. CurveItem
// will be destroyed when removeCurve is called on PlotSceneWidget (or,
// equivalently, on SceneCurve destruction)
//
CurveItem *curveItem = new CurveItem(curve);
// add the CurveItem to the Graphics Scene
scene()->addItem(curveItem);
//
// The CurveItem is aimed at calculating the transformations between the curve data
// coordinates and the PlotSceneWidget pixel coordinates.
// The CurveItem delegates the painting to specialized painters, which can be
// line painers, dot painters, histogram painters, and so on.
//
// Let's create a LinePainter to connect points on the plot with lines:
// Pass the curve item as parameter in the LinePainter constructor
// The curveItem takes the ownership of the line painter.
//
LinePainter *linePainter = new LinePainter(curveItem);
linePainter->setLineColor(Qt::green); //  colour the lines
// setData on the curve
QVector<double> xData, yData;
// fill the vectors xData and yData as you like, then....
// ...
//
curve->setData(xData, yData);
Why ownership of CurveItem and LinePainter is passed to SceneCurve and CurveItem respectively?
This particular implementation allows you to create the CurveItem and one or more LinePainter objects and forget about their memory management. It is strongly suggested to use addCurve and removeCurve(const QString&) methods to add and remove curves to and from the PlotSceneWidget
See also
addCurve
removeCurve(const QString&) This aspect must be taken into account when your application allows curve deletion at runtime. In other cases, you never want to worry about deleting the objects you create and attach to your plot to add curves or decorate them. This is accomplished by Qt QObject children deletion and careful design of parent-children hierarchy in QGraphicsPlot library.
Some more details about item deletion.
CurveItem is a QGraphicsObject and when it's added to a QGraphicsScene through QGraphicsScene::addItem the ownership is taken by the QGraphicsScene. This means that every CurveItem is deleted on scene deletion, i.e. on PlotSceneWidget deletion, since the plot scene is a child of PlotSceneWidget.
SceneCurve is created by PlotSceneWidget::addCurve as a child of PlotSceneWidget. Each curve is thus deleted on PlotSceneWidget destruction.
LinePainter, as in the example above, must be constructed by passing a CurveItem in its constructor. All ItemPainterInterface implementations, such as LinePainter, must inherit from QObject and the parent must be a CurveItem, as you can see in the LinePainter implementation. In this way, on CurveItem deletion, the LinePainter is automatically deleted, as a child of CurveItem.
Curve removal.
You can remove a SceneCurve at runtime by calling PlotSceneWidget::removeCurve. This method will delete the associated CurveItem (and all its painters, such as LinePainter, for example) and then delete the SceneCurve itself.
See also
removeCurve
addCurve
Using external scales
External scales can be used and they can be useful when the plot is zoomed and the plot internal axes fall out of the zoom area.
See also
ExternalScaleWidget
QGraphicsPlotItem() [2/2]
QGraphicsPlotItem::QGraphicsPlotItem (bool initDefaultAxes, QGraphicsItem * parent = nullptr) explicit
~QGraphicsPlotItem()
QGraphicsPlotItem::~QGraphicsPlotItem () virtual
Member Function Documentation
addAxis()
ScaleItem * QGraphicsPlotItem::addAxis (ScaleItem::Orientation o, ScaleItem::Id id, ScaleItem * associatedAxis)
References associatedAxis(), ScaleItem::Horizontal, installPlotGeometryChangeListener(), ScaleItem::orientation(), perr, removeAxis(), scaleItem(), ScaleItem::Vertical, AxisCouple::xAxis, and AxisCouple::yAxis.
addConfigurableObjects()
void QGraphicsPlotItem::addConfigurableObjects (const QString & title, QObject * object)
add an object which is configurable through its Qt properties.
Parameters
title in the configuration dialog of the plot the object properties will appear under a tab widget with title as the title page.
object the object whose properties are selected and configurable. May be a widget for example, or a graphics object item.
See also
removeConfigurableObjects
addCurve() [1/3]
SceneCurve * QGraphicsPlotItem::addCurve (const QString & name)
Creates a new curve with the given name and automatically associates it to the x bottom axis and y left axis.
Returns
the new curve just created. You can configure its properties using this return value.
Parameters
name the name with which the curve is marked and identified.
References addCurve(), xScaleItem(), and yScaleItem().
addCurve() [2/3]
SceneCurve * QGraphicsPlotItem::addCurve (const QString & name, ScaleItem * xScaleItem, ScaleItem * yScaleItem)
Creates a new curve with the given name and attachs the curve to the specified x and y ScaleItems (axes).
Use this method instead of the one provided above to attach the curve to a couple of axes different from the x bottom and y left default axes.
References curveAboutToBeDestroyed(), curveAdded(), ScaleItem::installAxisChangeListener(), perr, xScaleItem(), and yScaleItem().
addCurve() [3/3]
void QGraphicsPlotItem::addCurve (SceneCurve * curve)
References curveAboutToBeDestroyed(), curveAdded(), SceneCurve::getXAxis(), SceneCurve::getYAxis(), ScaleItem::installAxisChangeListener(), and SceneCurve::name().
Referenced by addCurve().
addLineCurve()
SceneCurve * QGraphicsPlotItem::addLineCurve (const QString & name, ScaleItem * xScaleI = NULL, ScaleItem * yScaleI = NULL)
adds and configures a curve with a LinePainter
This methods adds a new curve to the plot. The curve is represented in the plot by lines joining its points.
This method is equivalent to the calls to
SceneCurve *c = graphicsPlot->addCurve(name);
CurveItem *curveItem = new CurveItem(c);
graphicsPlot->scene()->addItem(curveItem);
c->installCurveChangeListener(curveItem);
LinePainter *lp = new LinePainter(curveItem);
The colour is automatically chosen.
References curveAboutToBeDestroyed(), curveAdded(), ColorPalette::getColor(), ScaleItem::installAxisChangeListener(), SceneCurve::installCurveChangeListener(), LinePainter::setLineColor(), xScaleItem(), and yScaleItem().
appendData [1/2]
void QGraphicsPlotItem::appendData (const QString & curveName, const QVector< double > & xData, const QVector< double > & yData) virtual slot
References SceneCurve::addPoints(), perr, qstoc, and update().
appendData [2/2]
void QGraphicsPlotItem::appendData (const QString & curveName, double x, double y) virtual slot
References SceneCurve::addPoint(), perr, qstoc, and update().
associatedAxis()
ScaleItem * QGraphicsPlotItem::associatedAxis (ScaleItem::Id otherAxisId) const
Referenced by addAxis(), and ScaleItem::paint().
associatedOriginPosPercentage()
QPair< double, double > QGraphicsPlotItem::associatedOriginPosPercentage (ScaleItem::Id xAxisId, ScaleItem::Id yAxisId, bool * ok) const
Referenced by ScaleItem::paint().
axesManager()
AxesManager * QGraphicsPlotItem::axesManager () const
returns the reference to the AxesManager.
See also
AxesManager
The AxesManager class manages the axes in the plot and their origins.
backgroundColor()
QColor QGraphicsPlotItem::backgroundColor () const
boundingRect
QRectF QGraphicsPlotItem::boundingRect () const slot
Referenced by ScaleItem::paint(), and ScaleItem::ScaleItem().
boundsChanged()
void QGraphicsPlotItem::boundsChanged () virtual
References SceneCurve::invalidateCache(), and scaleItem().
Referenced by setXScaleEnabled(), and setYScaleEnabled().
clear()
void QGraphicsPlotItem::clear ()
References clearAxes(), getCurves(), and ScaleItem::Vertical.
clearAxes()
void QGraphicsPlotItem::clearAxes (bool all = false, ScaleItem::Orientation o = ScaleItem::Vertical)
Removes the axes from the plot.
Parameters
all true: all axes (horizontal and vertical) are removed
all false: only the axes with the specified orientation are removed
Referenced by clear().
clicked
void QGraphicsPlotItem::clicked (const QPointF & pos) signal
the plot was clicked at the position pos
Parameters
pos the point where the click took place.
Referenced by mouseReleaseEvent().
contextMenuEvent()
void QGraphicsPlotItem::contextMenuEvent (QGraphicsSceneContextMenuEvent * event) protected
References createContextMenu().
createContextMenu
QMenu * QGraphicsPlotItem::createContextMenu () virtual slot
References executePropertyDialog(), and saveData().
Referenced by contextMenuEvent().
curveAboutToBeDestroyed() [1/2]
void QGraphicsPlotItem::curveAboutToBeDestroyed (const QString & name, bool deleteCurve = true)
References curveAboutToBeRemoved(), SceneCurve::curveItem(), SceneCurve::getXAxis(), SceneCurve::getYAxis(), perr, qstoc, and ScaleItem::removeAxisChangeListener().
curveAboutToBeDestroyed [2/2]
void QGraphicsPlotItem::curveAboutToBeDestroyed (QObject * crv) protected slot
this is a protected slot connected to the destroyed() signal of a SceneCurve
This method is involved when the users calls delete on a SceneCurve instead of using the removeCurve(const QString& name) method of the PlotSceneWidget, which is the recommended way to remove a curve from the plot.
References curveAboutToBeDestroyed(), and SceneCurve::name().
Referenced by addCurve(), addLineCurve(), and curveAboutToBeDestroyed().
curveAboutToBeRemoved
void QGraphicsPlotItem::curveAboutToBeRemoved (SceneCurve * c) signal
this signal is emitted when a curve is removed from the plot
Any class interested in knowing when a curve is removed (e.g. MarkerItem) must be connected to this signal, which is emitted right before the SceneCurve passed as parameter is removed.
Parameters
curve a reference to the curve being removed
Note
When this signal is emitted, the curve axes have not been already detached (they are available) and also the associated CurveItem is still available.
See also
CurveItem
ScaleItem
CurveAddded
Referenced by curveAboutToBeDestroyed().
curveAdded
void QGraphicsPlotItem::curveAdded (SceneCurve * curve) signal
This signal notifies that the curve has been added to the plot.
Parameters
curve the new curve
Note
The AxisChangeListener on the x and y axes has been installed on the plot when this signal is emitted. The curve has already been inserted in the internal list of curves. This means it is available through getCurves and findCurve. This does not mean that a CurveItem has already been installed on the curve. Always check for curveItem() returning NULL. If you use addLineCurve, then the curve has a CurveItem already associated when the signal is emitted.
Referenced by addCurve(), and addLineCurve().
curvesForAxes()
QList< SceneCurve * > QGraphicsPlotItem::curvesForAxes (ScaleItem::Id axisId, ScaleItem::Orientation orientation) const
returns the list of curves that are attached to the provided axisId with Orientation orientation
References SceneCurve::associatedXAxisId(), SceneCurve::associatedYAxisId(), and ScaleItem::Horizontal.
defaultXAxisOriginPosPercentage()
double QGraphicsPlotItem::defaultXAxisOriginPosPercentage () const
returns the origin position (in percentage between 0.0 and 1.0) of the default x scale item (the one that the PlotSceneWidget always creates automatically)
Axes are placed with a position with respect to each other defined by this value, expressed in percentage from 0.0 to 1.0. By default, the axes have both 0.0 as position percentage value
See also
originPosPercentage
defaultYAxisOriginPosPercentage
References originPosPercentage(), and xScaleItem().
defaultYAxisOriginPosPercentage()
double QGraphicsPlotItem::defaultYAxisOriginPosPercentage () const
returns the origin position (in percentage between 0.0 and 1.0) of the default y scale item (the one that the PlotSceneWidget always creates automatically)
See also
defaultXAxisOriginPosPercentage
originPosPercentage
References originPosPercentage(), and yScaleItem().
executePropertyDialog
void QGraphicsPlotItem::executePropertyDialog () slot
References PropertyDialog::configureTabs(), PropertyDialog::setSettingsKey(), and PropertyDialog::show().
Referenced by createContextMenu().
findCurve()
SceneCurve * QGraphicsPlotItem::findCurve (const QString & name)
finds the curve with the provided name
Returns
the curve with the given name or NULL if not present
Parameters
name the name to look for
getClosest()
QList< SceneCurve * > QGraphicsPlotItem::getClosest (QPointF & closestPos, int * closestIndex, const QPointF & viewPos)
retrieve the list of curves that are closest to the viewPos point in view coordinates. The closestPos point is the point, in scene coordinates, closest to the viewPos and belonging to the closest curves. The closestIndex is the x axis index coordinate of the closest point.
The returned list contains more than one curve if they overlap in the same point. Otherwise, the list will contain at most one curve.
Parameters
closestPos the position of the closest point, in scene coordinates.
viewPos the position, in view coordinates, whose curve's closest point must be searched
closestIndex the index with which you can retrieve the data in the data vector of the closest curve(s).
An example can be found in the MarkerItem::mouseClickEvent method
If no closest curve is found, the returned list is empty, the closestPos is a null point and the closest index is set to -1.
closestPos is passed by reference closestIndex is a pointer to an integer that will point to the index of the data vector associated to the closest point in the closest curve viewPos is the position in view coordinates, it may represent, as in MarkerItem::mouseClickEvent, the point where a click event has taken place in the QGraphicsPlotItem.
See also
MarkerItem::mouseClickEvent
References SceneCurve::data(), SceneCurve::dataSize(), SceneCurve::points(), Data::size(), Data::xData, and Data::yData.
Referenced by MarkerItem::mouseClickEvent().
getCurves()
QList< SceneCurve * > QGraphicsPlotItem::getCurves () const
returns a list of all curves belonging to this plot
Referenced by clear(), MarkerItem::mouseClickEvent(), and saveData().
getPoints()
QList< Point * > QGraphicsPlotItem::getPoints () const
installMouseEventListener()
void QGraphicsPlotItem::installMouseEventListener (MouseEventListener * l)
installPlotGeometryChangeListener()
void QGraphicsPlotItem::installPlotGeometryChangeListener (PlotGeometryEventListener * l)
Referenced by addAxis().
invTransform() [1/3]
double QGraphicsPlotItem::invTransform (const double pt, ScaleItem * scaleItem) const
transforms a double in scene coordinates into a double in scaleItem coordinates
Parameters
pt the x or y coordinate of the point you want to transform, in scene coordinates
scaleItem the ScaleItem on which to calculate the transformed value.
Returns
the value of the transformed point, in the scaleItem coordinates.
See also
invTransform(const double pt, ScaleItem* scaleItem) const
transform
References ScaleItem::Horizontal, ScaleItem::lowerBound, ScaleItem::orientation(), perr, ScaleItem::plotAreaH, ScaleItem::plotAreaW, scaleItem(), ScaleItem::upperBound, and ScaleItem::Vertical.
invTransform() [2/3]
QPointF QGraphicsPlotItem::invTransform (const QPointF & pSceneCoord)
transforms a QPointF in scene coordinates into a QPointF containing the x and y values in the x and y axis scale coordinates.
This method operates on the default x and y scale items, the ones returned by xScaleItem and yScaleItem. If you want to transform according to other scale items use the invTransform(const double pt, ScaleItem* scaleItem) method instead.
See also
invTransform(const double pt, ScaleItem* scaleItem) const
transform
References invTransform(), perr, xScaleItem(), and yScaleItem().
Referenced by invTransform().
invTransform() [3/3]
QPointF QGraphicsPlotItem::invTransform (const QPointF & pSceneCoord, ScaleItem * xScaleItem, ScaleItem * yScaleItem) const
References ScaleItem::lowerBound, perr, ScaleItem::plotAreaH, ScaleItem::plotAreaW, ScaleItem::upperBound, xScaleItem(), and yScaleItem().
inZoom()
bool QGraphicsPlotItem::inZoom () const
returns the zoom state
Returns
true the plot is being zoomed
false the plot is not in zoom state
The plot enters the zoom state when the user selects a rectangular area with the left mouse button together with the Maiusc key.
Note
The plot is not in zoom state when the user scrolls the mouse wheel to scale the view.
itemChange()
QVariant QGraphicsPlotItem::itemChange (QGraphicsItem::GraphicsItemChange change, const QVariant & value) protected
legendItem()
LegendItem * QGraphicsPlotItem::legendItem () const
legendVisible()
bool QGraphicsPlotItem::legendVisible () const
loadConfigurationProperties()
void QGraphicsPlotItem::loadConfigurationProperties ()
References SettingsLoader::loadConfiguration().
mouseDoubleClickEvent()
void QGraphicsPlotItem::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) protected
References MouseEventListener::mouseDoubleClickEvent().
mouseMoveEvent()
void QGraphicsPlotItem::mouseMoveEvent (QGraphicsSceneMouseEvent * event) protected
d_ptr->mouseMovingPoint = mapToScene(event->pos());
References MouseEventListener::mouseMoveEvent(), and update().
mousePressEvent()
void QGraphicsPlotItem::mousePressEvent (QGraphicsSceneMouseEvent * event) protected
References MouseEventListener::mousePressEvent(), and mSwitchAxesCurvesForeground().
mouseReleaseEvent()
void QGraphicsPlotItem::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected
References clicked(), MouseEventListener::mouseClickEvent(), and MouseEventListener::mouseReleaseEvent().
mouseZoomEnabled()
bool QGraphicsPlotItem::mouseZoomEnabled () const
returns the mouse zoom enable state
Returns
true the user is able to zoom with the mouse (while the Control key is simultaneously pressed.
false the mouse zoomer is disabled
See also
setMouseZoomEnabled
mSwitchAxesCurvesForeground()
void QGraphicsPlotItem::mSwitchAxesCurvesForeground () protected
Referenced by mousePressEvent().
originPosPercentage()
double QGraphicsPlotItem::originPosPercentage (ScaleItem * scaleIt) const
returns the origin position (in percentage between 0.0 and 1.0) of the scale item passed as parameter
Axes are placed with a position with respect to each other defined by this value, expressed in percentage from 0.0 to 1.0. By default, the axes have both 0.5 as position percentage value, meaning that they intersect in the middle of each other.
References ScaleItem::Horizontal, ScaleItem::orientation(), ScaleItem::Vertical, AxisCouple::xAxis, AxisCouple::xOriginPosPercentage, AxisCouple::yAxis, and AxisCouple::yOriginPosPercentage.
Referenced by defaultXAxisOriginPosPercentage(), and defaultYAxisOriginPosPercentage().
paint()
void QGraphicsPlotItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) protected
plotAreaChanged
void QGraphicsPlotItem::plotAreaChanged (const QSizeF & newSize) signal
notifies that the plot area has changed
Parameters
newSize the new size of the plot area
Note
newSize takes into account the transform() being applied to the view. The area is calculated by scaling the plotRect property according to the m11 and m22 elements of the transform matrix.
plotRect()
QRectF QGraphicsPlotItem::plotRect () const
Referenced by Point::updatePosition(), Point::updateXPos(), and Point::updateYPos().
plotRectChanged
void QGraphicsPlotItem::plotRectChanged (const QRectF & newRect) signal
The plot rectangle has changed.
Parameters
newRect the new rectangle containing the plot.
Plot Rect property.
It takes into account the sceneRect adjusted with the plotAreaPercentageWidth, plotAreaTopLeftXPercentage, plotAreaPercentageHeight and plotAreaTopLeftYPercentage properties. For this, newRect does not always coincide with the scene rect.
Note
The rectangle does not take into account the transform being applied, if any. For that purpose, please see plotAreaChanged
See also
plotAreaChanged
refreshPeriod()
int QGraphicsPlotItem::refreshPeriod () const
returns the refresh period of the internal timer used to refresh the scene when manualSceneUpdate is turned on.
Returns
the period in milliseconds of the internal timer. -1 is returned if the timer is not active, i.e. manualSceneUpdate is false
See also
setManualSceneUpdate
manualSceneUpdate
setRefreshPeriod
removeAxis [1/2]
void QGraphicsPlotItem::removeAxis (QObject * axis) protected slot
References removePlotGeometryChangeListener().
Referenced by addAxis().
removeAxis() [2/2]
void QGraphicsPlotItem::removeAxis (ScaleItem::Id id)
removeConfigurableObjects()
void QGraphicsPlotItem::removeConfigurableObjects (const QString & title)
removes an object which was previously added with addConfigurableObjects with the given title.
Parameters
title in the configuration dialog of the plot the object properties will appear under a tab widget with title as the title page.
See also
addConfigurableObjects
removeMouseEventListener()
void QGraphicsPlotItem::removeMouseEventListener (MouseEventListener * l)
removePlotGeometryChangeListener()
void QGraphicsPlotItem::removePlotGeometryChangeListener (PlotGeometryEventListener * l)
Referenced by removeAxis().
resize
void QGraphicsPlotItem::resize (const QSizeF & s) slot
References update().
saveData
void QGraphicsPlotItem::saveData () slot
References PlotSceneWidgetSaver::errorMessage(), PlotSceneWidgetSaver::fileName(), getCurves(), PlotSceneWidgetSaver::save(), ScaleItem::scaleLabelInterface(), ScaleLabelInterface::TimeScale, ScaleLabelInterface::type(), and xScaleItem().
Referenced by createContextMenu().
scaleItem()
ScaleItem * QGraphicsPlotItem::scaleItem (ScaleItem::Id id) const
returns the ScaleItem associated to the argument.
Returns
the ScaleItem associated to the id. The ScaleItem must have previously been programmatically added through the AxesManager.
Returns NULL if the ScaleItem with the provided Id was not added programmatically.
See also
AxesManager::addCouple
Referenced by addAxis(), boundsChanged(), invTransform(), and transform().
setBackgroundColor
void QGraphicsPlotItem::setBackgroundColor (const QColor & c) slot
setData [1/2]
void QGraphicsPlotItem::setData (const QString & curveName, const QVector< double > & xData, const QVector< double > & yData) virtual slot
References perr, qstoc, SceneCurve::setData(), and update().
setData [2/2]
void QGraphicsPlotItem::setData (const QString & curveName, const QVector< double > & yData) virtual slot
References perr, qstoc, SceneCurve::setData(), and update().
setDefaultXAxisOriginPosPercentage
void QGraphicsPlotItem::setDefaultXAxisOriginPosPercentage (double percent) slot
Changes the position of the default x axis.
The default x axis is the axis that PlotSceneWidget always creates for you and places at the position 0.5 by default.
Parameters
percent the value of the new position for the default x axis
See also
setOriginPosPercentage
setDefaultYAxisOriginPosPercentage
If you added custom axes, then use the setOriginPosPercentage method instead.
References setOriginPosPercentage(), and xScaleItem().
setDefaultYAxisOriginPosPercentage
void QGraphicsPlotItem::setDefaultYAxisOriginPosPercentage (double percent) slot
Changes the position of the default y axis.
The default y axis is the axis that PlotSceneWidget always creates for you and places at the position 0.5 by default.
Parameters
percent the value of the new position for the default y axis
See also
setOriginPosPercentage
setDefaultXAxisOriginPosPercentage
If you added custom axes, then use the setOriginPosPercentage method instead.
References setOriginPosPercentage(), and yScaleItem().
setGeometry
void QGraphicsPlotItem::setGeometry (const QRectF & r) slot
References update().
setLegendVisible
void QGraphicsPlotItem::setLegendVisible (bool visible) slot
setManualUpdate
void QGraphicsPlotItem::setManualUpdate (bool manual) slot
This is an important optimization that acts on the QGraphicsView::ViewportUpdateMode that comes into relevance when you have several items that must be fastly drawn.
This property sets the ViewportUpdateMode to QGraphicsView::NoViewportUpdate meaning that QGraphicsView will never update its viewport when the scene changes; the user is expected to control all updates. This mode disables all (potentially slow) item visibility testing in QGraphicsView, and is suitable for scenes that either require a fixed frame rate, or where the viewport is otherwise updated externally.
Note
When you enable manual scene update, then you must call setRefreshPeriod with the desired refresh period of the scene, which typically must be equal to the fastest refresh rate needed by the fastest item.
Calling setManualSceneUpdate with a false parameter, restores QGraphicsScene default ViewportUpdateMode, which is QGraphicsView::MinimalViewportUpdate, according to the Qt documentation.
Parameters
manual true update is managed by an internal timer. setRefreshPeriod must be called with a greater than zero value in order to activate the timer and have the scene refreshed with that interval.
manual false the update is set to QGraphicsView::MinimalViewportUpdate, the default Qt setting for the ViewportUpdateMode property. The internal refresh timer, if previously activated and started with a valid setRefreshPeriod method call is automatically stopped for you. The timer is not deleted, it is just stopped, so that a subsequent call to setManualSceneUpdate with a true parameter automatically restarts the timer with the timeout previously set with setRefreshPeriod. In this way, a second manual mode activation does not need another call to setRefreshPeriod. A call to setRefreshPeriod with zero or a negative value instead produces the destruction of the timer.
See also
setRefreshPeriod
refreshPeriod
manualSceneUpdate
setMouseZoomEnabled
void QGraphicsPlotItem::setMouseZoomEnabled (bool en) slot
Enables the zoom with the mouse, when the Ctrl key and the left mouse button are pressed.
Parameters
en the Ctrl+Left mouse button zoomes the area drawn by the mouse
false the mouse zoomer is disabled.
See also
mouseZoomEnabled
setOriginPosPercentage
void QGraphicsPlotItem::setOriginPosPercentage (ScaleItem * scaleIt, double percent) slot
sets the position of the origin of the given scale item to the specified percent value, in percentage terms from 0 to 1.0
Parameters
scaleIt the scale item whose position you want to change
percent the value of the position, from 0 to 1.0.
If you did not add additional axes by yourself, then you might want to use the shortcut methods setDefaultXAxisOriginPosPercentage and setDefaultYAxisOriginPosPercentage.
See also
setDefaultXAxisOriginPosPercentage
setDefaultYAxisOriginPosPercentage
References ScaleItem::Horizontal, ScaleItem::orientation(), ScaleItem::updateLabelsCache(), and ScaleItem::Vertical.
Referenced by setDefaultXAxisOriginPosPercentage(), and setDefaultYAxisOriginPosPercentage().
setRefreshPeriod
void QGraphicsPlotItem::setRefreshPeriod (int period) slot
sets the refresh period of the internal timer used to refresh the scene when manualSceneUpdate is turned on.
Parameters
period the interval, in milliseconds of the internal timer.
The period must be greater than 0. If zero or a negative value is passed, then the internal timer is stopped and destroyed. When invoked with a value greater than zero, an internal refresh timer is created, with objectName "refreshTimer", its interval is set to period and the timer is started. At each timeout, the scene is refreshed. The period must be as fast as to ensure that the fastest item in the scene is updated in time.
See also
setManualSceneUpdate
manualSceneUpdate
refreshPeriod
References update().
setXAxisAutoscaleEnabled
void QGraphicsPlotItem::setXAxisAutoscaleEnabled (bool en) slot
Shortcut to enable/disable the autoscale on the x axis.
calls xScaleItem()->setAxisAutoscaleEnabled(en)
References ScaleItem::setAxisAutoscaleEnabled(), and xScaleItem().
setXAxisLowerBound
void QGraphicsPlotItem::setXAxisLowerBound (double xlb) slot
Shortcut to access the x axis and set the bound.
References ScaleItem::setLowerBound(), and xScaleItem().
setXAxisUpperBound
void QGraphicsPlotItem::setXAxisUpperBound (double xub) slot
Shortcut to access the x axis and set the bound.
References ScaleItem::setUpperBound(), and xScaleItem().
setXScaleEnabled
void QGraphicsPlotItem::setXScaleEnabled (bool en) slot
References boundsChanged(), ScaleItem::setVisible(), and ScaleItem::xBottom.
setYAxisAutoscaleEnabled
void QGraphicsPlotItem::setYAxisAutoscaleEnabled (bool en) slot
Shortcut to enable/disable the autoscale on the x axis.
calls xScaleItem()->setAxisAutoscaleEnabled(en)
References ScaleItem::setAxisAutoscaleEnabled(), and yScaleItem().
setYAxisLowerBound
void QGraphicsPlotItem::setYAxisLowerBound (double ylb) slot
Shortcut to access the y axis and set the bound.
References ScaleItem::setLowerBound(), and yScaleItem().
setYAxisUpperBound
void QGraphicsPlotItem::setYAxisUpperBound (double yub) slot
Shortcut to access the y axis and set the bound.
References ScaleItem::setUpperBound(), and yScaleItem().
setYScaleEnabled
void QGraphicsPlotItem::setYScaleEnabled (bool en) slot
References boundsChanged(), ScaleItem::setVisible(), and ScaleItem::yLeft.
smoothPixmapTransform()
bool QGraphicsPlotItem::smoothPixmapTransform () const
transform()
double QGraphicsPlotItem::transform (const double x, ScaleItem * scaleItem) const
transforms a value on the scaleItem axis in axis coordinates into a value in scene coordinates inside the plot rect.
Parameters
x the value of the point on the ScaleItem axis
scaleItem the axis on which to make the calculation.
Returns
a coordinate in scene coordinates, representing the x axis point mapped into a point in the scene coordinate
References ScaleItem::Horizontal, ScaleItem::lowerBound, ScaleItem::orientation(), perr, ScaleItem::plotArea(), ScaleItem::plotAreaH, ScaleItem::plotAreaW, scaleItem(), and ScaleItem::upperBound.
update()
void QGraphicsPlotItem::update (const QRectF & area = QRectF()) protected
Referenced by appendData(), mouseMoveEvent(), resize(), setData(), setGeometry(), and setRefreshPeriod().
xAxisAutoscaleEnabled()
bool QGraphicsPlotItem::xAxisAutoscaleEnabled () const
shortcut to get the axis autoscale mode from the xScaleItem()
Returns
xScaleItem()->axisAutoscaleEnabled()
References ScaleItem::axisAutoscaleEnabled, and xScaleItem().
xAxisLowerBound()
double QGraphicsPlotItem::xAxisLowerBound () const
shortcut to get the axis bound from the xScaleItem()
Returns
xScaleItem->lowerBound
References ScaleItem::lowerBound, and xScaleItem().
xAxisUpperBound()
double QGraphicsPlotItem::xAxisUpperBound () const
shortcut to get the axis bound from the xScaleItem()
Returns
xScaleItem->upperBound
References ScaleItem::upperBound, and xScaleItem().
xScaleEnabled()
bool QGraphicsPlotItem::xScaleEnabled () const
References ScaleItem::xBottom.
xScaleItem()
ScaleItem * QGraphicsPlotItem::xScaleItem () const
shortcut to retrieve the x scale item (ScaleItem::xBottom) which is always created by default.
Returns
the x bottom scale item, if not removed programmatically, NULL otherwise.
References ScaleItem::xBottom.
Referenced by addCurve(), addLineCurve(), defaultXAxisOriginPosPercentage(), invTransform(), saveData(), setDefaultXAxisOriginPosPercentage(), setXAxisAutoscaleEnabled(), setXAxisLowerBound(), setXAxisUpperBound(), xAxisAutoscaleEnabled(), xAxisLowerBound(), and xAxisUpperBound().
yAxisAutoscaleEnabled()
bool QGraphicsPlotItem::yAxisAutoscaleEnabled () const
shortcut to get the axis autoscale mode from the yScaleItem()
Returns
yScaleItem()->axisAutoscaleEnabled()
References ScaleItem::axisAutoscaleEnabled, and yScaleItem().
yAxisLowerBound()
double QGraphicsPlotItem::yAxisLowerBound () const
shortcut to get the axis bound from the yScaleItem()
Returns
yScaleItem->lowerBound
References ScaleItem::lowerBound, and yScaleItem().
yAxisUpperBound()
double QGraphicsPlotItem::yAxisUpperBound () const
shortcut to get the axis bound from the yScaleItem()
Returns
yScaleItem->upperBound
References ScaleItem::upperBound, and yScaleItem().
yScaleEnabled()
bool QGraphicsPlotItem::yScaleEnabled () const
References ScaleItem::yLeft.
yScaleItem()
ScaleItem * QGraphicsPlotItem::yScaleItem () const
shortcut to retrieve the y scale item (ScaleItem::yLeft) which is always created by default.
Returns
the y left scale item, if not removed programmatically, NULL otherwise.
References ScaleItem::yLeft.
Referenced by addCurve(), addLineCurve(), defaultYAxisOriginPosPercentage(), invTransform(), setDefaultYAxisOriginPosPercentage(), setYAxisAutoscaleEnabled(), setYAxisLowerBound(), setYAxisUpperBound(), yAxisAutoscaleEnabled(), yAxisLowerBound(), and yAxisUpperBound().
zoomer()
QGraphicsZoomer * QGraphicsPlotItem::zoomer () const
zoomLevel()
int QGraphicsPlotItem::zoomLevel () const
returns the zoom level of the zoomer.
The minimum value returned by this call is 1 and it means that no zoom is currently applied. A value of 2 means that the plot has been zoomed 1 time, a value of 3 means that the plot has been zoomed 2 times and so on.
Returns
the zoom level: 1 means no zoom, 2 means zoomed once and so on...
Property Documentation
backgroundColor
QColor QGraphicsPlotItem::backgroundColor read write
defaultXAxisOriginPosPercentage
double QGraphicsPlotItem::defaultXAxisOriginPosPercentage read write
defaultYAxisOriginPosPercentage
double QGraphicsPlotItem::defaultYAxisOriginPosPercentage read write
legendVisible
bool QGraphicsPlotItem::legendVisible read write
mouseZoomEnabled
bool QGraphicsPlotItem::mouseZoomEnabled read write
refreshPeriod
int QGraphicsPlotItem::refreshPeriod read write
xScaleEnabled
bool QGraphicsPlotItem::xScaleEnabled read write
yScaleEnabled
bool QGraphicsPlotItem::yScaleEnabled read write
The documentation for this class was generated from the following files:
qgraphicsplotitem.h
qgraphicsplotitem.cpp