cumbia-qtcontrols-ng: QuCircularPlotConfigurator Class Reference
QuCircularPlotConfigurator Class Reference
#include <qucircularplotconfigurator.h>
Public Member Functions
QuCircularPlotConfigurator ()
void configure (QuCircularPlotCurve *c, int curvecnt)
QString m_get_id (const QuCircularPlotCurve *c)
Constructor & Destructor Documentation
QuCircularPlotConfigurator()
QuCircularPlotConfigurator::QuCircularPlotConfigurator ()
Member Function Documentation
configure()
void QuCircularPlotConfigurator::configure (QuCircularPlotCurve * c, int curvecnt)
References m_get_id(), QuCircularPlotCurve::pen(), qstoc, and QuCircularPlotCurve::setPen().
Referenced by QuCircularPlotEngine::addCurve(), and QuCircularPlotEngine::setData().
m_get_id()
QString QuCircularPlotConfigurator::m_get_id (const QuCircularPlotCurve * c)
References QuCircularPlotCurve::source().
Referenced by configure().
The documentation for this class was generated from the following files:
qucircularplotconfigurator.h
qucircularplotconfigurator.cpp