cumbia-qtcontrols-ng: QuCircularPlotCurve Class Reference
QuCircularPlotCurve Class Reference
#include <qucircularplotcurve.h>
Public Member Functions
QuCircularPlotCurve (const QString &src, QuCircularPlotCurveListener *l, const QPen &p=QPen(QColor(Qt::gray), 0.0f))
virtual ~QuCircularPlotCurve ()
const QVector< double > & x_data () const
const QVector< double > & y_data () const
QString source () const
void setData (const QVector< double > &x, const QVector< double > &y)
int size () const
void setPen (const QPen &p)
QPen pen () const
double ymax () const
double ymin () const
void minmax_update ()
void select (int idx)
void deselect ()
int selected () const
bool isEditable () const
void setEditable (bool e)
Constructor & Destructor Documentation
QuCircularPlotCurve()
QuCircularPlotCurve::QuCircularPlotCurve (const QString & src, QuCircularPlotCurveListener * l, const QPen & p = QPen(QColor(Qt::gray), 0.0f))
~QuCircularPlotCurve()
QuCircularPlotCurve::~QuCircularPlotCurve () virtual
Member Function Documentation
deselect()
void QuCircularPlotCurve::deselect ()
Referenced by QuCircularPlotEngine::clearSelection().
isEditable()
bool QuCircularPlotCurve::isEditable () const
minmax_update()
void QuCircularPlotCurve::minmax_update ()
pen()
QPen QuCircularPlotCurve::pen () const
Referenced by QuCircularPlotConfigurator::configure().
select()
void QuCircularPlotCurve::select (int idx)
Referenced by QuCircularPlotEngine::select().
selected()
int QuCircularPlotCurve::selected () const
Referenced by QuCircularPlotEngine::clearSelection(), QuCircularPlotEngine::moveSelection(), QuCircularPlotEngine::setData(), and QuCircularPlotSelectionValue::update().
setData()
void QuCircularPlotCurve::setData (const QVector< double > & x, const QVector< double > & y)
Referenced by QuCircularPlotEngine::setData().
setEditable()
void QuCircularPlotCurve::setEditable (bool e)
setPen()
void QuCircularPlotCurve::setPen (const QPen & p)
Referenced by QuCircularPlotConfigurator::configure().
size()
int QuCircularPlotCurve::size () const
Referenced by QuCircularPlotEngine::setData().
source()
QString QuCircularPlotCurve::source () const
Referenced by QuCircularPlotConfigurator::m_get_id(), QuCircularPlotEngine::moveSelection(), and QuCircularPlotEngine::select().
x_data()
const QVector< double > & QuCircularPlotCurve::x_data () const
Referenced by QuCircularPlotEngine::select().
y_data()
const QVector< double > & QuCircularPlotCurve::y_data () const
Referenced by QuCircularPlotEngine::moveSelection(), QuCircularPlotEngine::select(), QuCircularPlotEngine::setData(), and QuCircularPlotSelectionValue::update().
ymax()
double QuCircularPlotCurve::ymax () const
ymin()
double QuCircularPlotCurve::ymin () const
The documentation for this class was generated from the following files:
qucircularplotcurve.h
qucircularplotcurve.cpp