cumbia-qtcontrols-ng: ExternalScales Class Reference
ExternalScales Class Reference
#include <externalscales.h>
Public Member Functions
ExternalScales (QWidget *parent=0)
~ExternalScales ()
Constructor & Destructor Documentation
ExternalScales()
ExternalScales::ExternalScales (QWidget * parent = 0) explicit
References SceneCurve::installCurveChangeListener(), KCAMEL, KDARKBLUE, KDARKCYAN, KDARKPINK, KDARKWATER, KGRAY, KVERYDARKVIOLET, KYELLOW, SceneCurve::name(), and SceneCurve::setBufferSize().
~ExternalScales()
ExternalScales::~ExternalScales ()
The documentation for this class was generated from the following files:
externalscales.h
externalscales.cpp