cumbia-qtcontrols-ng: PropertyDialog Class Reference
PropertyDialog Class Reference
#include <propertydialog.h>
Public Slots
void show ()
Public Member Functions
PropertyDialog (QGraphicsPlotItem *sceneWidget)
virtual ~PropertyDialog ()
void configureTabs (const QMap< QString, QObject * > objectsMap)
void setSettingsKey (const QString &key)
Constructor & Destructor Documentation
PropertyDialog()
PropertyDialog::PropertyDialog (QGraphicsPlotItem * sceneWidget) explicit
~PropertyDialog()
PropertyDialog::~PropertyDialog () virtual
Member Function Documentation
configureTabs()
void PropertyDialog::configureTabs (const QMap< QString, QObject * > objectsMap) inline
Referenced by QGraphicsPlotItem::executePropertyDialog().
setSettingsKey()
void PropertyDialog::setSettingsKey (const QString & key) inline
Referenced by QGraphicsPlotItem::executePropertyDialog().
show
void PropertyDialog::show () slot
not working yet...
References qstoc.
Referenced by QGraphicsPlotItem::executePropertyDialog().
The documentation for this class was generated from the following files:
propertydialog.h
propertydialog.cpp