cumbia-qtcontrols-ng: SceneCurve Class Reference
SceneCurve Class Reference
#include <scenecurve.h>
Public Slots
void setBufferSize (int bufSiz)
void setXDataIsOrdered (bool ordered)
void setYDataIsOrdered (bool ordered)
Public Member Functions
SceneCurve (QGraphicsPlotItem *sceneWidget, const QString &name, ScaleItem *xAxis, ScaleItem *yAxis)
Constructor of a SceneCurve object.
virtual ~SceneCurve ()
QGraphicsPlotItem * plot () const
returns a reference to the PlotSceneWidget to which this curve has been attached.
QGraphicsScene * scene () const
returns the QGraphicsScene used by the PlotSceneWidget.
int dataSize () const
returns the current number of XYItems (points) in the curve.
int bufferSize () const
returns the curve buffer size
QString name () const
the curve name
virtual QRectF addPoint (double x, double y)
Add a couple of points (x,y) to the curve.
virtual QRectF addPoints (const QVector< double > &xData, const QVector< double > &yData)
This convenience method appends a vector of data to a scalar curve.
Data * data () const
void setData (const QVector< double > &xData, const QVector< double > &yData)
void setData (const QVector< double > &yData)
void installCurveChangeListener (CurveChangeListener *listener)
QList< CurveChangeListener * > curveChangeListeners () const
void removeCurveChangeListener (CurveChangeListener *listener)
void removeCurveItem ()
Removes a CurveItem from the list of items associated to the curve.
void setCurveItem (CurveItem *curveItem)
This method adds to the list of CurveItem objects an already allocated CurveItem.
CurveItem * curveItem () const
Returns the last curve item that was attached to the curve.
ScaleItem::Id associatedXAxisId () const
ScaleItem::Id associatedYAxisId () const
virtual double getMinX () const
virtual double getMinY () const
virtual double getMaxX () const
virtual double getMaxY () const
ScaleItem * getXAxis () const
ScaleItem * getYAxis () const
void invalidateCache ()
void invalidateXCache ()
void invalidateYCache ()
void xAxisBoundsChanged (double xl, double xu)
x axis bounds notification
void yAxisBoundsChanged (double yl, double yu)
y axis bounds notification
void axisAutoscaleChanged (ScaleItem::Orientation o, bool autoscale)
when a scale item changes its autoscale state, if autoscale is enabled it is necessary to recalculate all max and min values of the curves.
virtual void tickStepLenChanged (double)
virtual void labelsFormatChanged (const QString &)
bool xDataIsOrdered () const
bool yDataIsOrdered () const
const QPointF * points ()
returns a list of points in scene coordinates. Each point is the transformation in scene coordinates of the x and y corresponding value.
virtual void plotAreaChanged (const QRectF &newRect)
notifies when the canvas area changes.
Public Member Functions inherited from AxisChangeListener
AxisChangeListener ()
virtual void xAxisBoundsChanged (double lower, double upper)=0
x axis bounds notification
virtual void yAxisBoundsChanged (double lower, double upper)=0
y axis bounds notification
virtual void axisAutoscaleChanged (ScaleItem::Orientation o, bool autoscale)=0
x axis auto scale property change notification
virtual void plotAreaChanged (const QRectF &newRect)=0
notifies when the canvas area changes.
virtual void tickStepLenChanged (double value)=0
notifies listeners about tick step len changes.
virtual void labelsFormatChanged (const QString &newFormat)=0
when the labels format changes, labelsFormatChanged is used
Properties
int bufferSize
bool xDataIsOrdered
bool yDataIsOrdered
Constructor & Destructor Documentation
SceneCurve()
SceneCurve::SceneCurve (QGraphicsPlotItem * sceneWidget, const QString & name, ScaleItem * xAxis, ScaleItem * yAxis) explicit
Constructor of a SceneCurve object.
Constructs a new SceneCurve, which collects a number of XYItems internally.
Parameters
sceneWidget the PlotSceneWidget to which the curve must belong
name a compulsory name representing the curve.
xAxis a reference to an existing ScaleItem to use as y axis
yAxis a reference to an existing ScaleItem to use as y axis
Concepts.
Each curve belongs to a PlotSceneWidget and has two axes associated. The SceneCurve implements the AxisChangeListener interface in order to know when the axes bounds change and the axis autoScale property changes.
Curve drawing.
The SceneCurve does not draw anything on the scene. Its just recollects data and keeps a list of points whose coordinates map the real points into the plot coordinate system. In order to draw, you must create a CurveItem and then attach it to the SceneCurve, normally constructing a CurveItem with the SceneCurve as parameter.
See also
CurveItem::CurveItem
Example. Adding a curve to a PlotSceneWidget
SceneCurve *curve = mPlot->addCurve("Curve Name");
// if you want no more than bufsize points on the curve
int bufsize = 1000;
curve->setBufferSize(bufsize);
// Create the effective curve painter!
// Just pass the curve in the constructor
CurveItem *curveItem = new CurveItem(curve);
// add the CurveItem to the Graphics Scene
scene()->addItem(curveItem);
//
// The CurveItem is aimed at calculating the transformations between the curve data
// coordinates and the PlotSceneWidget pixel coordinates.
// The CurveItem delegates the painting to specialized painters, which can be
// line painers, dot painters, histogram painters, and so on.
//
// Let's create a LinePainter to connect points on the plot with lines:
// Pass the curve item as parameter in the LinePainter constructor
//
LinePainter *linePainter = new LinePainter(curveItem);
linePainter->setLineColor(Qt::green); //  colour the lines
// setData on the curve
QVector<double> xData, yData;
// fill the vectors xData and yData as you like, then....
// ...
//
curve->setData(xData, yData);
Item painters ownership
The CurveItem takes the ownership of every installed ItemPainterInterface implementation instance. This means that all the installed ItemPainterInterface objects are deleted on CurveItem deletion.
CurveItem ownership
If you call PlotSceneWidget::removeCurve, then the associated CurveItem is deleted. If you delete a SceneCurve without invoking PlotSceneWidget::removeCurve (bad), then the associated CurveItem is deleted again for you. This means that once installed on a SceneCurve, the ownership of the CurveItem is taken by the SceneCurve. With the term install we mean the
CurveItem *curveItem = new CurveItem(curve);
instruction.
Obtaining the CurveItem QGraphicsObject objects associated to the SceneCurve
An internal reference to the (unique) CurveItem object is kept in order to be able to provide it to the users of SceneCurve. The method curveItem() can be used to retrieve a reference to the unique CurveItem attached to the curve. For instance to change the colour of the line at any time, having a reference to a SceneCurve:
LinePainter *currentLinePainter = curve->curveItem()->linePainter();
currentLinePainter->setLineColor(Qt::blue);
Note
The code above only works if a unique LinePainter was installed, just like in the Example in the previous paragraph. If a LinePainter coexists with a DotsPainter, for instance, you need to carefully read the note below.
Multiple ItemPainterInterface implementation instances can be installed on a CurveItem. If they all are QObject-derived, then a Qt property can be used to distinguish between different painters. For instance:
linePainter->setProperty("type", "Lines");
Moreover, the ItemPainterInterface::type virtual method, which is implemented by all ItemPainterInterface derived classes provides a key to distinguish among predefined and user defined painters. The ItemPainterInterface can be statically casted to the correct class type.
See also
ItemPainterInterface::type()
Retrieving an installed LinePainter, given a SceneCurve
CurveItem *curveItem = sceneCurve->curveItem();
// get all the installed item painters
QList<ItemPainterInterface *>itemPainters = curveItem->itemPainters();
// and look for the LinePainter
foreach(ItemPainterInterface *ipi, itemPainters)
{
  if(ipi->type() == ItemPainterInterface::Line)
    static_cast<LinePainter *>(ipi)->setLineColor(Qt::darkRed);
}
The alias property.
The Qt alias property can be set so that some objects can use it to display the curve name instead of the string returned by SceneCurve::name method.
Note: NaN values
The NaN y values are mapped on the same y as the previous y value. If the first point of a curve is NaN, then the lower bound is chosen for the NaN representation.
Important: it is up to the painter to evidentiate a NaN value. This must be done inspecting the y data value of a point.
See also
PlotSceneWidget
Data
CurveItem
LinePainter
Dotspainter
HistogramPainter
ItemPainterInterface
References name(), and plotAreaChanged().
~SceneCurve()
SceneCurve::~SceneCurve () virtual
Member Function Documentation
addPoint()
QRectF SceneCurve::addPoint (double x, double y) virtual
Add a couple of points (x,y) to the curve.
References CurveChangeListener::itemAdded().
Referenced by addPoints(), and QGraphicsPlotItem::appendData().
addPoints()
QRectF SceneCurve::addPoints (const QVector< double > & xData, const QVector< double > & yData) virtual
This convenience method appends a vector of data to a scalar curve.
Note
scalar data.
References addPoint().
Referenced by QGraphicsPlotItem::appendData().
associatedXAxisId()
ScaleItem::Id SceneCurve::associatedXAxisId () const
Referenced by QGraphicsPlotItem::curvesForAxes().
associatedYAxisId()
ScaleItem::Id SceneCurve::associatedYAxisId () const
Referenced by QGraphicsPlotItem::curvesForAxes().
axisAutoscaleChanged()
void SceneCurve::axisAutoscaleChanged (ScaleItem::Orientation o, bool autoscale) virtual
when a scale item changes its autoscale state, if autoscale is enabled it is necessary to recalculate all max and min values of the curves.
Actually, if autoscale was previously disabled, at each addPoint call or addPoints call, the maximum and minimum values of the curves were not calculated.
Implements AxisChangeListener.
References ScaleItem::Horizontal, and ScaleItem::Vertical.
bufferSize()
int SceneCurve::bufferSize () const
returns the curve buffer size
Returns
the number of maximum items allowed in the curve.
When the number of items of the curve reaches bufferSize, the oldes item is removed.
See also
setBufferSize
curveChangeListeners()
QList< CurveChangeListener * > SceneCurve::curveChangeListeners () const
curveItem()
CurveItem * SceneCurve::curveItem () const
Returns the last curve item that was attached to the curve.
Note
This method can be used when you are sure that only one CurveItem has been associated to the curve, because it returns only the last element in the list of the potentially multiple CurveItem objects associated to the SceneCurve.
See also
curveItems
Referenced by QGraphicsPlotItem::curveAboutToBeDestroyed(), LegendItem::getColor(), LegendItem::paint(), ScaleItem::setBoundsFromCurves(), and setCurveItem().
data()
Data * SceneCurve::data () const
Referenced by DotsPainter::draw(), LinePainter::draw(), StepsPainter::draw(), QGraphicsPlotItem::getClosest(), MarkerItem::paint(), points(), PlotSceneWidgetSaver::save(), and ScaleItem::setBoundsFromCurves().
dataSize()
int SceneCurve::dataSize () const
returns the current number of XYItems (points) in the curve.
Referenced by CircleItemSet::draw(), DotsPainter::draw(), LinePainter::draw(), StepsPainter::draw(), QGraphicsPlotItem::getClosest(), MarkerItem::paint(), and PlotSceneWidgetSaver::save().
getMaxX()
double SceneCurve::getMaxX () const virtual
getMaxY()
double SceneCurve::getMaxY () const virtual
getMinX()
double SceneCurve::getMinX () const virtual
getMinY()
double SceneCurve::getMinY () const virtual
getXAxis()
ScaleItem * SceneCurve::getXAxis () const
Referenced by QGraphicsPlotItem::addCurve(), QGraphicsPlotItem::curveAboutToBeDestroyed(), and MarkerItem::paint().
getYAxis()
ScaleItem * SceneCurve::getYAxis () const
Referenced by QGraphicsPlotItem::addCurve(), QGraphicsPlotItem::curveAboutToBeDestroyed(), and MarkerItem::paint().
installCurveChangeListener()
void SceneCurve::installCurveChangeListener (CurveChangeListener * listener)
Referenced by QGraphicsPlotItem::addLineCurve(), AgingCircles::AgingCircles(), ExternalScales::ExternalScales(), and XYSceneTest::XYSceneTest().
invalidateCache()
void SceneCurve::invalidateCache ()
Referenced by QGraphicsPlotItem::boundsChanged(), and plotAreaChanged().
invalidateXCache()
void SceneCurve::invalidateXCache ()
Referenced by xAxisBoundsChanged().
invalidateYCache()
void SceneCurve::invalidateYCache ()
Referenced by yAxisBoundsChanged().
labelsFormatChanged()
virtual void SceneCurve::labelsFormatChanged (const QString &) inline virtual
not needed. Empty bodies.
Implements AxisChangeListener.
name()
QString SceneCurve::name () const
the curve name
Each curve has a name by means of which it is identified by the owning plot (PlotSceneWidget)
Referenced by QGraphicsPlotItem::addCurve(), QGraphicsPlotItem::curveAboutToBeDestroyed(), LegendItem::curveRemoved(), ExternalScales::ExternalScales(), LegendItem::getColor(), LegendItem::paint(), MarkerItem::paint(), PlotSceneWidgetSaver::save(), and SceneCurve().
plot()
QGraphicsPlotItem * SceneCurve::plot () const
returns a reference to the PlotSceneWidget to which this curve has been attached.
plotAreaChanged()
void SceneCurve::plotAreaChanged (const QRectF & newRect) virtual
notifies when the canvas area changes.
In some cases, when the axis is placed on the right or at the bottom of the plot, the labels might require more space, and the plot area must be reduced.
Parameters
newRect the new rectangle
Implements AxisChangeListener.
References invalidateCache().
Referenced by SceneCurve().
points()
const QPointF * SceneCurve::points ()
returns a list of points in scene coordinates. Each point is the transformation in scene coordinates of the x and y corresponding value.
Returns
a vector of QPointF representing the points of the curve in scene coordinates
Parameters
curve the SceneCurve which owns the data.
Note
Marks x and y pos cache as valid, because this method calculates the position of each point in scene coordinates.
References data(), and Data::size().
Referenced by CircleItemSet::draw(), DotsPainter::draw(), LinePainter::draw(), StepsPainter::draw(), QGraphicsPlotItem::getClosest(), and MarkerItem::paint().
removeCurveChangeListener()
void SceneCurve::removeCurveChangeListener (CurveChangeListener * listener)
removeCurveItem()
void SceneCurve::removeCurveItem ()
Removes a CurveItem from the list of items associated to the curve.
When a CurveItem is destroyed, this method must be called in order to tell the SceneCurve that a CurveItem has been removed. This method removes the CurveItem from the internal list of CurveItem objects
See also
CurveItem::~CurveItem
scene()
QGraphicsScene * SceneCurve::scene () const
returns the QGraphicsScene used by the PlotSceneWidget.
It internally calls plot()->scene();
setBufferSize
void SceneCurve::setBufferSize (int bufSiz) slot
References CurveChangeListener::bufferSizeChanged().
Referenced by AgingCircles::AgingCircles(), ExternalScales::ExternalScales(), and XYSceneTest::XYSceneTest().
setCurveItem()
void SceneCurve::setCurveItem (CurveItem * curveItem)
This method adds to the list of CurveItem objects an already allocated CurveItem.
An internal list of CurveItem objects is kept in order to be able to provide to the users of SceneCurve a list of associated CurveItems.
References curveItem().
setData() [1/2]
void SceneCurve::setData (const QVector< double > & xData, const QVector< double > & yData)
Referenced by QGraphicsPlotItem::setData().
setData() [2/2]
void SceneCurve::setData (const QVector< double > & yData)
References CurveChangeListener::fullVectorUpdate().
setXDataIsOrdered
void SceneCurve::setXDataIsOrdered (bool ordered) slot
setYDataIsOrdered
void SceneCurve::setYDataIsOrdered (bool ordered) slot
tickStepLenChanged()
virtual void SceneCurve::tickStepLenChanged (double) inline virtual
not needed. Empty bodies.
Implements AxisChangeListener.
xAxisBoundsChanged()
void SceneCurve::xAxisBoundsChanged (double lower, double upper) virtual
x axis bounds notification
Parameters
lower the new lower bound
upper the new upper bound
Implements AxisChangeListener.
References invalidateXCache().
xDataIsOrdered()
bool SceneCurve::xDataIsOrdered () const
yAxisBoundsChanged()
void SceneCurve::yAxisBoundsChanged (double lower, double upper) virtual
y axis bounds notification
Parameters
lower the new lower bound
upper the new upper bound
Implements AxisChangeListener.
References invalidateYCache().
yDataIsOrdered()
bool SceneCurve::yDataIsOrdered () const
Property Documentation
bufferSize
int SceneCurve::bufferSize read write
xDataIsOrdered
bool SceneCurve::xDataIsOrdered read write
yDataIsOrdered
bool SceneCurve::yDataIsOrdered read write
The documentation for this class was generated from the following files:
scenecurve.h
scenecurve.cpp