cumbia-qtcontrols-ng: QuNumericW Class Reference
QuNumericW Class Reference
#include <qunumericwidget.h>
Public Slots
void setValue (double v)
void setShowApply (bool s)
void setMaximum (double v)
void setMinimum (double v)
void setIntDigits (int i)
void setDecDigits (int d)
Signals
void valueChanged (double v)
void minimumChanged (double m)
void maximumChanged (double M)
void intDigitsChanged (int id)
void decDigitsChanged (int dd)
void clicked (double val)
Public Member Functions
QuNumericW (QWidget *parent=nullptr)
virtual ~QuNumericW ()
QSize sizeHint () const
QSize minimumSizeHint () const
double maximum () const
double value () const
double minimum () const
int intDigits () const
int decDigits () const
bool showApply () const
Protected Member Functions
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void mouseDoubleClickEvent (QMouseEvent *event)
void mouseMoveEvent (QMouseEvent *event)
void wheelEvent (QWheelEvent *event)
void leaveEvent (QEvent *event)
void paintEvent (QPaintEvent *event)
void changeEvent (QEvent *e)
Properties
int intDigits
int decDigits
double value
double maximum
double minimum
bool showApply
Constructor & Destructor Documentation
QuNumericW()
QuNumericW::QuNumericW (QWidget * parent = nullptr) explicit
References clicked(), decDigitsChanged(), intDigitsChanged(), maximumChanged(), minimumChanged(), and valueChanged().
~QuNumericW()
QuNumericW::~QuNumericW () virtual
Member Function Documentation
changeEvent()
void QuNumericW::changeEvent (QEvent * e) protected
clicked
void QuNumericW::clicked (double val) signal
apply button clicked while the display value is val
Referenced by QuNumericW().
decDigits()
int QuNumericW::decDigits () const
decDigitsChanged
void QuNumericW::decDigitsChanged (int dd) signal
Referenced by QuNumericW().
intDigits()
int QuNumericW::intDigits () const
intDigitsChanged
void QuNumericW::intDigitsChanged (int id) signal
Referenced by QuNumericW().
leaveEvent()
void QuNumericW::leaveEvent (QEvent * event) protected
maximum()
double QuNumericW::maximum () const
maximumChanged
void QuNumericW::maximumChanged (double M) signal
Referenced by QuNumericW().
minimum()
double QuNumericW::minimum () const
minimumChanged
void QuNumericW::minimumChanged (double m) signal
Referenced by QuNumericW().
minimumSizeHint()
QSize QuNumericW::minimumSizeHint () const
mouseDoubleClickEvent()
void QuNumericW::mouseDoubleClickEvent (QMouseEvent * event) protected
mouseMoveEvent()
void QuNumericW::mouseMoveEvent (QMouseEvent * event) protected
mousePressEvent()
void QuNumericW::mousePressEvent (QMouseEvent * event) protected
mouseReleaseEvent()
void QuNumericW::mouseReleaseEvent (QMouseEvent * event) protected
paintEvent()
void QuNumericW::paintEvent (QPaintEvent * event) protected
setDecDigits
void QuNumericW::setDecDigits (int d) slot
sets number of deciam digits to be displayed
Parameters
d number of digits
Referenced by QuNumericControlW::onUpdate().
setIntDigits
void QuNumericW::setIntDigits (int i) slot
returns the minimum value of the widget
Returns
min val sets number of integer digits to be displayed
Parameters
i number of digits
Referenced by QuNumericControlW::onUpdate().
setMaximum
void QuNumericW::setMaximum (double v) slot
Referenced by QuNumericControlW::onUpdate().
setMinimum
void QuNumericW::setMinimum (double v) slot
Referenced by QuNumericControlW::onUpdate().
setShowApply
void QuNumericW::setShowApply (bool s) slot
setValue
void QuNumericW::setValue (double v) slot
Referenced by QuNumericControlW::onUpdate().
showApply()
bool QuNumericW::showApply () const
sizeHint()
QSize QuNumericW::sizeHint () const
value()
double QuNumericW::value () const
valueChanged
void QuNumericW::valueChanged (double v) signal
Referenced by QuNumericW().
wheelEvent()
void QuNumericW::wheelEvent (QWheelEvent * event) protected
Property Documentation
decDigits
int QuNumericW::decDigits read write
intDigits
int QuNumericW::intDigits read write
maximum
double QuNumericW::maximum read write
minimum
double QuNumericW::minimum read write
showApply
bool QuNumericW::showApply read write
value
double QuNumericW::value read write
The documentation for this class was generated from the following files:
qunumericwidget.h
qunumericwidget.cpp