cumbia-qtcontrols-ng: ItemPainterInterface Class Reference
ItemPainterInterface Class Reference abstract
A class that can be installed in a CurveItem which is delegated to drawing.
#include <itempainterinterface.h>
Public Types
enum Type {
Line = 0 , Dot , Cross , Histogram ,
Step , Pie , CircleItemSet , User = 100
}
Public Member Functions
ItemPainterInterface ()
virtual ~ItemPainterInterface ()
virtual void draw (SceneCurve *curve, QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)=0
the drawing method.
virtual CurveItem * curveItem () const =0
virtual QSizeF elementSize () const =0
the size of each drawn element
virtual int type () const =0
virtual QPen pen () const =0
Detailed Description
A class that can be installed in a CurveItem which is delegated to drawing.
Member Enumeration Documentation
Type
enum ItemPainterInterface::Type
Enumerator
Line
Dot
Cross
Histogram
Step
Pie
CircleItemSet
User
Constructor & Destructor Documentation
ItemPainterInterface()
ItemPainterInterface::ItemPainterInterface () inline
~ItemPainterInterface()
virtual ItemPainterInterface::~ItemPainterInterface () inline virtual
Member Function Documentation
curveItem()
virtual CurveItem * ItemPainterInterface::curveItem () const pure virtual
Implemented in CircleItemSet, DotsPainter, HistogramPainter, LinePainter, and StepsPainter.
draw()
virtual void ItemPainterInterface::draw (SceneCurve * curve, QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0) pure virtual
the drawing method.
This method is invoked by CurveItem inside paint method. You can obtain the points of the curve in scene coordinates by calling curve->points and the size of the points by means of curve->dataSize. It may be necessary to call painter->save() and painter->restore() at the beginning and end of the drawing. Each draw method of each installed ItemPainterInterface is actually invoked in sequence without saving and restoring the painter state for you.
See also
CurveItem
LinePainter
DotsPainter
Implemented in CircleItemSet, DotsPainter, HistogramPainter, LinePainter, and StepsPainter.
Referenced by CurveItem::paint().
elementSize()
virtual QSizeF ItemPainterInterface::elementSize () const pure virtual
the size of each drawn element
This size is used by the classes that use ItemPainterInterface to know how much extra space is needed in order to calculate the bounding rect of the CurveItem or other geometrical properties.
For instance, if you are drawing circles, then this method should return the radius of the circle, so that CurveItem knows how much space has to be added to the curve bounds in order to correcly draw the items.
If you are drawing lines, then this size can be 0x0 since the connecting lines do not require extra space to be calculated. If you use a particular pen width, then you may want to return its width in order to be sure that CurveItem takes care of this space.
See also
CurveItem
Implemented in CircleItemSet, DotsPainter, HistogramPainter, LinePainter, and StepsPainter.
Referenced by CurveItem::itemAboutToBeRemoved(), and CurveItem::itemAdded().
pen()
virtual QPen ItemPainterInterface::pen () const pure virtual
Implemented in DotsPainter, HistogramPainter, LinePainter, and StepsPainter.
Referenced by LegendItem::getColor().
type()
virtual int ItemPainterInterface::type () const pure virtual
Implemented in CircleItemSet, DotsPainter, HistogramPainter, LinePainter, and StepsPainter.
The documentation for this class was generated from the following file:
itempainterinterface.h