cumbia-qtcontrols-ng: QuCircularPlotI Class Reference
QuCircularPlotI Class Reference
A QGraphicsItem (QGraphicsObject) representing a circular plot.
#include <qucircularplotitem.h>
Public Slots
void update ()
void setData (const QString &src, const QVector< double > &xdata, const QVector< double > &ydata)
Public Member Functions
QuCircularPlotI (QGraphicsItem *parent, const QSize &siz=QSize(200, 200))
virtual ~QuCircularPlotI ()
QuCircularPlotEngine * engine () const
QRectF boundingRect () const
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
Protected Member Functions
QVariant itemChange (GraphicsItemChange change, const QVariant &value)
Detailed Description
A QGraphicsItem (QGraphicsObject) representing a circular plot.
QuCircularPlotI is a QGraphicsItem (actually, a QGraphicsObject) draws curves on a circle, between a lower and an upper bound circumference
See also
QuCircularPlotEngine
QuCircularPlotWidget
Refer to the QuCircularPlotEngine for further information and an example.
QuCircularPlotI *ni = new QuCircularPlotI(nullptr, QSize(300, 300));
QuCircularPlotEngine *pie = ni->engine();
// now use QuCircularPlotEngine interface to configure the plot
QuCircularPlotW and QuCircularPlotItem share the same painting engine to draw their contents using the classical QWidget and the QGraphicsView/QGraphicsScene technologies respectively.
Four QuCircularPlotI items in a QGraphicsScene. One is zoomed.
Constructor & Destructor Documentation
QuCircularPlotI()
QuCircularPlotI::QuCircularPlotI (QGraphicsItem * parent, const QSize & siz = QSize(200,200))
References update().
~QuCircularPlotI()
QuCircularPlotI::~QuCircularPlotI () virtual
Member Function Documentation
boundingRect()
QRectF QuCircularPlotI::boundingRect () const
engine()
QuCircularPlotEngine * QuCircularPlotI::engine () const
itemChange()
QVariant QuCircularPlotI::itemChange (GraphicsItemChange change, const QVariant & value) protected
paint()
void QuCircularPlotI::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget)
setData
void QuCircularPlotI::setData (const QString & src, const QVector< double > & xdata, const QVector< double > & ydata) slot
References update().
update
void QuCircularPlotI::update () slot
Referenced by QuCircularPlotI(), and setData().
The documentation for this class was generated from the following files:
qucircularplotitem.h
qucircularplotitem.cpp