cumbia-qtcontrols-ng: QuNumericEngine Class Reference
QuNumericEngine Class Reference
#include <qunumericengine.h>
Public Slots
void setValue (double v)
void setMaximum (double m)
void setMinimum (double m)
void setIntDigits (int i)
void setDecDigits (int d)
void click (const QPointF &pos)
void click (const QPointF &pos, bool up)
void setShowApply (bool show)
Signals
void valueChanged (double v)
void minimumChanged (double m)
void maximumChanged (double M)
void intDigitsChanged (int id)
void decDigitsChanged (int dd)
void applyClicked (double val)
Public Member Functions
QuNumericEngine (const QFont &f)
virtual ~QuNumericEngine ()
void contextMenuEvent (const QPointF &pos)
void mousePressEvent (const QPointF &pos)
void mouseMoveEvent (const QPointF &pos)
void mouseReleaseEvent (const QPointF &pos)
void mouseDoubleClickEvent (const QPointF &pos)
void wheelEvent (const QPointF &pos, double delta)
double value () const
double minimum () const
double maximum () const
void paint (QPainter *p, const QRectF &rect, QWidget *widget)
void setFont (const QFont &f)
QSizeF minimumSize ()
Public Attributes
QuApplyNumEngineData d
Constructor & Destructor Documentation
QuNumericEngine()
QuNumericEngine::QuNumericEngine (const QFont & f) explicit
References QuApplyNumEngineData::arrow_hei, QuApplyNumEngineData::bm, d, QuApplyNumEngineData::data, QuApplyNumEngineData::decDig, QuApplyNumEngineData::digits, QuApplyNumEngineData::font, QuApplyNumEngineData::font_scale, QuApplyNumEngineData::intDig, QuApplyNumEngineData::last_applied_data, QuApplyNumEngineData::lm, QuApplyNumEngineData::max, QuApplyNumEngineData::max_d, QuApplyNumEngineData::min, QuApplyNumEngineData::min_d, QuApplyNumEngineData::mouse_down, QuApplyNumEngineData::rm, QuApplyNumEngineData::show_apply, and QuApplyNumEngineData::um.
~QuNumericEngine()
QuNumericEngine::~QuNumericEngine () virtual
Member Function Documentation
applyClicked
void QuNumericEngine::applyClicked (double val) signal
Referenced by click().
click [1/2]
void QuNumericEngine::click (const QPointF & pos) slot
References click().
Referenced by click(), mouseReleaseEvent(), and wheelEvent().
click [2/2]
void QuNumericEngine::click (const QPointF & pos, bool up) slot
References QuANRect::Apply, applyClicked(), d, QuApplyNumEngineData::data, QuApplyNumEngineData::last_applied_data, QuApplyNumEngineData::max, QuApplyNumEngineData::min, value(), and valueChanged().
contextMenuEvent()
void QuNumericEngine::contextMenuEvent (const QPointF & pos)
decDigitsChanged
void QuNumericEngine::decDigitsChanged (int dd) signal
Referenced by setDecDigits().
intDigitsChanged
void QuNumericEngine::intDigitsChanged (int id) signal
Referenced by setIntDigits().
maximum()
double QuNumericEngine::maximum () const
References d, and QuApplyNumEngineData::max_d.
maximumChanged
void QuNumericEngine::maximumChanged (double M) signal
Referenced by setMaximum().
minimum()
double QuNumericEngine::minimum () const
References d, and QuApplyNumEngineData::min_d.
minimumChanged
void QuNumericEngine::minimumChanged (double m) signal
Referenced by setMinimum().
minimumSize()
QSizeF QuNumericEngine::minimumSize ()
References QuApplyNumEngineData::arrow_hei, QuApplyNumEngineData::bm, d, QuApplyNumEngineData::decDig, QuApplyNumEngineData::digits, QuApplyNumEngineData::font, QuApplyNumEngineData::lm, QuApplyNumEngineData::maxcharw, QuApplyNumEngineData::minsiz, QuApplyNumEngineData::rm, QuApplyNumEngineData::show_apply, and QuApplyNumEngineData::um.
mouseDoubleClickEvent()
void QuNumericEngine::mouseDoubleClickEvent (const QPointF & pos)
mouseMoveEvent()
void QuNumericEngine::mouseMoveEvent (const QPointF & pos)
References d, and QuApplyNumEngineData::mouse_pos.
mousePressEvent()
void QuNumericEngine::mousePressEvent (const QPointF & pos)
References d, QuApplyNumEngineData::mouse_down, and QuApplyNumEngineData::mouse_pos.
mouseReleaseEvent()
void QuNumericEngine::mouseReleaseEvent (const QPointF & pos)
References click(), d, QuApplyNumEngineData::mouse_down, and QuApplyNumEngineData::mouse_pos.
paint()
void QuNumericEngine::paint (QPainter * p, const QRectF & rect, QWidget * widget)
References QuANRect::Apply, QuApplyNumEngineData::arrow_hei, CHECK_MARK, d, QuApplyNumEngineData::data, QuApplyNumEngineData::decDig, QuApplyNumEngineData::digitrects, QuApplyNumEngineData::digits, QuANRect::Dot, QuApplyNumEngineData::font_scale, QuApplyNumEngineData::intDig, QuApplyNumEngineData::last_applied_data, QuApplyNumEngineData::maxcharw, QuApplyNumEngineData::mouse_down, QuApplyNumEngineData::mouse_pos, QuApplyNumEngineData::show_apply, and QuANRect::Sign.
setDecDigits
void QuNumericEngine::setDecDigits (int d) slot
References d, QuApplyNumEngineData::data, QuApplyNumEngineData::decDig, decDigitsChanged(), QuApplyNumEngineData::digits, QuApplyNumEngineData::intDig, QuApplyNumEngineData::max, QuApplyNumEngineData::min, QuApplyNumEngineData::minsiz, and value().
setFont()
void QuNumericEngine::setFont (const QFont & f)
References QuApplyNumEngineData::arrow_hei, d, QuApplyNumEngineData::font, QuApplyNumEngineData::font_scale, and QuApplyNumEngineData::minsiz.
setIntDigits
void QuNumericEngine::setIntDigits (int i) slot
References d, QuApplyNumEngineData::decDig, QuApplyNumEngineData::digits, QuApplyNumEngineData::intDig, intDigitsChanged(), and QuApplyNumEngineData::minsiz.
setMaximum
void QuNumericEngine::setMaximum (double m) slot
References d, QuApplyNumEngineData::decDig, QuApplyNumEngineData::max, QuApplyNumEngineData::max_d, maximumChanged(), and QuApplyNumEngineData::min_d.
setMinimum
void QuNumericEngine::setMinimum (double m) slot
References d, QuApplyNumEngineData::decDig, QuApplyNumEngineData::max_d, QuApplyNumEngineData::min, QuApplyNumEngineData::min_d, and minimumChanged().
setShowApply
void QuNumericEngine::setShowApply (bool show) slot
References d, QuApplyNumEngineData::minsiz, and QuApplyNumEngineData::show_apply.
setValue
void QuNumericEngine::setValue (double v) slot
References d, QuApplyNumEngineData::data, QuApplyNumEngineData::decDig, QuApplyNumEngineData::max, QuApplyNumEngineData::max_d, QuApplyNumEngineData::min, QuApplyNumEngineData::min_d, perr, value(), and valueChanged().
value()
double QuNumericEngine::value () const
References d, QuApplyNumEngineData::data, and QuApplyNumEngineData::decDig.
Referenced by click(), setDecDigits(), and setValue().
valueChanged
void QuNumericEngine::valueChanged (double v) signal
Referenced by click(), and setValue().
wheelEvent()
void QuNumericEngine::wheelEvent (const QPointF & pos, double delta)
References click().
Member Data Documentation
d
QuApplyNumEngineData QuNumericEngine::d
Referenced by click(), maximum(), minimum(), minimumSize(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), paint(), QuNumericEngine(), setDecDigits(), setFont(), setIntDigits(), setMaximum(), setMinimum(), setShowApply(), setValue(), and value().
The documentation for this class was generated from the following files:
qunumericengine.h
qunumericengine.cpp