cumbia-qtcontrols-ng: QuZoomer Class Reference
QuZoomer Class Reference
#include <quzoomer.h>
Public Slots
void setZoomRect (const QRectF &r)
void moveZoom (const QPointF &p1, const QPointF &p2)
void unzoom ()
void zoomRectChanging (const QPointF &topl, const QPointF &botr)
void mapClick (const QPointF &p, const Qt::MouseButton butt, Qt::KeyboardModifiers mod)
Signals
void zoomChanged ()
void moved (double dx, double dy)
void clicked (const QPointF &p, const Qt::MouseButton butt, Qt::KeyboardModifiers mod)
Public Member Functions
QuZoomer (QObject *parent)
virtual ~QuZoomer ()
QRectF zoomRect () const
const QRectF & zoomArea () const
bool inZoom () const
int stackSize () const
bool rectChanging () const
bool viewportChanged () const
const QTransform & calculateTransform (const QRectF &r) const
const QTransform & transform () const
QPointF map (const QPointF &pt)
Constructor & Destructor Documentation
QuZoomer()
QuZoomer::QuZoomer (QObject * parent) explicit
~QuZoomer()
QuZoomer::~QuZoomer () virtual
Member Function Documentation
calculateTransform()
const QTransform & QuZoomer::calculateTransform (const QRectF & r) const
Referenced by QuCircularPlotEngine::paint().
clicked
void QuZoomer::clicked (const QPointF & p, const Qt::MouseButton butt, Qt::KeyboardModifiers mod) signal
Referenced by mapClick().
inZoom()
bool QuZoomer::inZoom () const
Referenced by QuCircularPlotEngine::paint().
map()
QPointF QuZoomer::map (const QPointF & pt)
mapClick
void QuZoomer::mapClick (const QPointF & p, const Qt::MouseButton butt, Qt::KeyboardModifiers mod) slot
References clicked().
moved
void QuZoomer::moved (double dx, double dy) signal
Referenced by moveZoom().
moveZoom
void QuZoomer::moveZoom (const QPointF & p1, const QPointF & p2) slot
References moved(), and zoomChanged().
rectChanging()
bool QuZoomer::rectChanging () const
Referenced by QuCircularPlotEngine::paint().
setZoomRect
void QuZoomer::setZoomRect (const QRectF & r) slot
References zoomChanged().
stackSize()
int QuZoomer::stackSize () const
transform()
const QTransform & QuZoomer::transform () const
Referenced by QuCircularPlotEngine::select().
unzoom
void QuZoomer::unzoom () slot
References zoomChanged().
viewportChanged()
bool QuZoomer::viewportChanged () const
zoomArea()
const QRectF & QuZoomer::zoomArea () const
Referenced by QuCircularPlotEngine::paint().
zoomChanged
void QuZoomer::zoomChanged () signal
Referenced by moveZoom(), setZoomRect(), unzoom(), and zoomRectChanging().
zoomRect()
QRectF QuZoomer::zoomRect () const
zoomRectChanging
void QuZoomer::zoomRectChanging (const QPointF & topl, const QPointF & botr) slot
References zoomChanged().
The documentation for this class was generated from the following files:
quzoomer.h
quzoomer.cpp