cumbia-qtcontrols-ng: HistogramPainter Class Reference
HistogramPainter Class Reference
#include <histogrampainter.h>
Public Slots
void setAutoWidth (bool aw)
void setWidth (double w)
void setBaseLine (double baseline)
void setColor (const QColor &c)
void setColorAt (int index, const QColor &c)
Public Member Functions
HistogramPainter (CurveItem *curveItem)
virtual void draw (SceneCurve *curve, QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
the drawing method.
virtual CurveItem * curveItem () const
virtual QSizeF elementSize () const
the size of each drawn element
virtual int type () const
QColor color () const
double width () const
double baseLine () const
bool autoWidth () const
QColor colorAt (int index) const
QPen pen () const
Implements the pen method of the ItemPainterInterface.
Public Member Functions inherited from ItemPainterInterface
ItemPainterInterface ()
virtual ~ItemPainterInterface ()
virtual void draw (SceneCurve *curve, QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)=0
the drawing method.
virtual CurveItem * curveItem () const =0
virtual QSizeF elementSize () const =0
the size of each drawn element
virtual int type () const =0
virtual QPen pen () const =0
Properties
double width
double baseLine
QColor color
bool autoWidth
Additional Inherited Members
Public Types inherited from ItemPainterInterface
enum Type {
Line = 0 , Dot , Cross , Histogram ,
Step , Pie , CircleItemSet , User = 100
}
Constructor & Destructor Documentation
HistogramPainter()
HistogramPainter::HistogramPainter (CurveItem * curveItem)
References curveItem(), CurveItem::installItemPainterInterface(), KBLUE, and KDARKBLUE.
Member Function Documentation
autoWidth()
bool HistogramPainter::autoWidth () const
baseLine()
double HistogramPainter::baseLine () const
color()
QColor HistogramPainter::color () const
colorAt()
QColor HistogramPainter::colorAt (int index) const
curveItem()
CurveItem * HistogramPainter::curveItem () const virtual
Implements ItemPainterInterface.
Referenced by HistogramPainter().
draw()
void HistogramPainter::draw (SceneCurve * curve, QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0) virtual
the drawing method.
This method is invoked by CurveItem inside paint method. You can obtain the points of the curve in scene coordinates by calling curve->points and the size of the points by means of curve->dataSize. It may be necessary to call painter->save() and painter->restore() at the beginning and end of the drawing. Each draw method of each installed ItemPainterInterface is actually invoked in sequence without saving and restoring the painter state for you.
See also
CurveItem
LinePainter
DotsPainter
Implements ItemPainterInterface.
elementSize()
QSizeF HistogramPainter::elementSize () const virtual
the size of each drawn element
This size is used by the classes that use ItemPainterInterface to know how much extra space is needed in order to calculate the bounding rect of the CurveItem or other geometrical properties.
For instance, if you are drawing circles, then this method should return the radius of the circle, so that CurveItem knows how much space has to be added to the curve bounds in order to correcly draw the items.
If you are drawing lines, then this size can be 0x0 since the connecting lines do not require extra space to be calculated. If you use a particular pen width, then you may want to return its width in order to be sure that CurveItem takes care of this space.
See also
CurveItem
Implements ItemPainterInterface.
pen()
QPen HistogramPainter::pen () const virtual
Implements the pen method of the ItemPainterInterface.
Returns
the pen used to draw the rects
Implements ItemPainterInterface.
setAutoWidth
void HistogramPainter::setAutoWidth (bool aw) slot
setBaseLine
void HistogramPainter::setBaseLine (double baseline) slot
setColor
void HistogramPainter::setColor (const QColor & c) slot
setColorAt
void HistogramPainter::setColorAt (int index, const QColor & c) slot
setWidth
void HistogramPainter::setWidth (double w) slot
type()
int HistogramPainter::type () const virtual
Implements ItemPainterInterface.
References ItemPainterInterface::Histogram.
width()
double HistogramPainter::width () const
Property Documentation
autoWidth
bool HistogramPainter::autoWidth read write
baseLine
double HistogramPainter::baseLine read write
color
QColor HistogramPainter::color read write
width
double HistogramPainter::width read write
The documentation for this class was generated from the following files:
histogrampainter.h
histogrampainter.cpp