cumbia-qtcontrols-ng: MouseEventListener Class Reference
MouseEventListener Class Reference
an abstract class that can be used to be notified when a mouse event takes place
#include <mouseeventlistener.h>
Public Member Functions
MouseEventListener ()
virtual void mousePressEvent (QGraphicsPlotItem *, QGraphicsSceneMouseEvent *)
virtual void mouseReleaseEvent (QGraphicsPlotItem *, QGraphicsSceneMouseEvent *)
virtual void mouseMoveEvent (QGraphicsPlotItem *, QGraphicsSceneMouseEvent *)
virtual void mouseClickEvent (QGraphicsPlotItem *, const QPointF &)
virtual void mouseDoubleClickEvent (QGraphicsPlotItem *, QGraphicsSceneMouseEvent *)
Detailed Description
an abstract class that can be used to be notified when a mouse event takes place
Mouse press, move, release and click event can be intercepted. In each method, a reference to the PlotSceneWidget that received the event is passed.
Constructor & Destructor Documentation
MouseEventListener()
MouseEventListener::MouseEventListener () inline
Member Function Documentation
mouseClickEvent()
virtual void MouseEventListener::mouseClickEvent (QGraphicsPlotItem * , const QPointF &) inline virtual
Reimplemented in MarkerItem.
Referenced by QGraphicsPlotItem::mouseReleaseEvent().
mouseDoubleClickEvent()
virtual void MouseEventListener::mouseDoubleClickEvent (QGraphicsPlotItem * , QGraphicsSceneMouseEvent *) inline virtual
Reimplemented in MarkerItem.
Referenced by QGraphicsPlotItem::mouseDoubleClickEvent().
mouseMoveEvent()
virtual void MouseEventListener::mouseMoveEvent (QGraphicsPlotItem * , QGraphicsSceneMouseEvent *) inline virtual
Referenced by QGraphicsPlotItem::mouseMoveEvent().
mousePressEvent()
virtual void MouseEventListener::mousePressEvent (QGraphicsPlotItem * , QGraphicsSceneMouseEvent *) inline virtual
Referenced by QGraphicsPlotItem::mousePressEvent().
mouseReleaseEvent()
virtual void MouseEventListener::mouseReleaseEvent (QGraphicsPlotItem * , QGraphicsSceneMouseEvent *) inline virtual
Reimplemented in MarkerItem.
Referenced by QGraphicsPlotItem::mouseReleaseEvent().
The documentation for this class was generated from the following file:
mouseeventlistener.h