cumbia-qtcontrols-ng: QuNumericI Class Reference
QuNumericI Class Reference
#include <qunumericitem.h>
Public Slots
void update ()
Public Member Functions
QuNumericI (QGraphicsItem *parent)
virtual ~QuNumericI ()
QRectF boundingRect () const
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
Protected Member Functions
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event)
void wheelEvent (QGraphicsSceneWheelEvent *event)
void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
Constructor & Destructor Documentation
QuNumericI()
QuNumericI::QuNumericI (QGraphicsItem * parent)
References update().
~QuNumericI()
QuNumericI::~QuNumericI () virtual
Member Function Documentation
boundingRect()
QRectF QuNumericI::boundingRect () const
contextMenuEvent()
void QuNumericI::contextMenuEvent (QGraphicsSceneContextMenuEvent * event) protected
hoverLeaveEvent()
void QuNumericI::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) protected
References update().
hoverMoveEvent()
void QuNumericI::hoverMoveEvent (QGraphicsSceneHoverEvent * event) protected
References update().
mouseDoubleClickEvent()
void QuNumericI::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) protected
mousePressEvent()
void QuNumericI::mousePressEvent (QGraphicsSceneMouseEvent * event) protected
References update().
mouseReleaseEvent()
void QuNumericI::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected
References update().
paint()
void QuNumericI::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget)
update
void QuNumericI::update () slot
Referenced by hoverLeaveEvent(), hoverMoveEvent(), mousePressEvent(), mouseReleaseEvent(), QuNumericI(), and wheelEvent().
wheelEvent()
void QuNumericI::wheelEvent (QGraphicsSceneWheelEvent * event) protected
References update().
The documentation for this class was generated from the following files:
qunumericitem.h
qunumericitem.cpp