cumbia-qtcontrols-ng: QuCircularPlotEngine Class Reference
QuCircularPlotEngine Class Reference
Engine shared by either QuCircularPlotItem or QuCircularPlotWidget that stores configuration and does all the painting and zooming and stores the data.
#include <qucircularplotengine.h>
Public Slots
void setYLowerBound (double m)
disable y axis autoscale and set the lower bound
void setYUpperBound (double m)
disable y axis autoscale and set the upper bound
void setXLowerBound (double m)
disable x axis autoscale and set the lower bound
void setXUpperBound (double m)
disable x axis autoscale and set the upper bound
void setXBounds (double xm, double xM)
void setYBounds (double ym, double yM)
void setXAutoscaleEnabled (bool en)
enable or disable the x axis autoscale
void setYAutoscaleEnabled (bool en)
enable or disable the y axis autoscale
void setScaleInverted (bool inve)
void setInnerRadiusFactor (float f)
void setOuterRadiusFactor (float f)
void setData (const QString &src, const QVector< double > &xdata, const QVector< double > &ydata)
void setShowValues (bool show)
void setShowPoints (bool show)
void setShowCurves (bool show)
void setShowYAxes (int count)
void setShowBounds (bool show)
void recalculateTxtFont ()
void setBackground (const QColor &c)
void setAxesColor (const QColor &c)
void setCurveEditRadius (float r)
void setCurveSelectionPointRadius (float r)
void select (const QPointF &p)
void moveSelection (const double &dx, const double &dy)
void clearSelection ()
Signals
void minimumChanged (double m)
void maximumChanged (double M)
void selected (const QPointF &p)
void closestPoint (const QList< QuCircularPlotCurve * > &curves, int idx, const QPointF &pt)
void dirty ()
void selectionChanged (QuCircularPlotCurve *c, int idx, double new_val)
void selectionChanged (QObject *o, const QString &curve, int idx, double new_val)
void clicked (const QPointF &p, const Qt::MouseButton butt, Qt::KeyboardModifiers mod)
void selectedYChanged (QuCircularPlotCurve *c)
selectedYChanged is emitted when a selection on one (or more) curve(s) is active and the y value for the selected curve index changes
Public Member Functions
struct qucircularplot_attributes & att ()
convenience alias for either a memeber or attributes method
struct qucircularplot_attributes & attributes ()
convenience alias for either a memeber or att method
QuCircularPlotEngine (QObject *parent, const QFont &f, QuZoomer *zoomer, QuCircularPlotCurveSelectionEvents *selev, QuZoomEvents *ze)
virtual ~QuCircularPlotEngine ()
QuCircularPlotCurve * addCurve (const QString &src)
QuCircularPlotCurve * findCurve (const QString &src) const
find a curve either by exact match or regexp
QuZoomer * zoomer () const
QuZoomEvents * zoomEvents () const
QObject * plot () const
double yLowerBound () const
double yUpperBound () const
double xLowerBound () const
double xUpperBound () const
QColor background () const
QColor axesColor () const
float innerRadiusFactor () const
float outerRadiusFactor () const
void paint (QPainter *p, const QRectF &rect, QWidget *widget)
void setFont (const QFont &f)
QSizeF minimumSize ()
void setOutOfBoundsTransform (OOBDistort *c)
bool showValues () const
bool showPoints () const
bool showCurves () const
bool showXAxis () const
int showYAxes () const
bool showBounds () const
bool scaleInverted () const
float curveEditRadius () const
float curveSelectedPointRadius () const
void addDrawable (QuCircularPlotDrawable_I *dra)
add a QuCircularPlotDrawable_I object which will be drawn within QuCircularPlotEngine::paint according to its z position
QList< QuCircularPlotDrawable_I * > drawables () const
QRectF boundingRect () const
virtual void onCurveBoundsChanged ()=0
Public Attributes
struct qucircularplot_attributes a
plot configuration
Detailed Description
Engine shared by either QuCircularPlotItem or QuCircularPlotWidget that stores configuration and does all the painting and zooming and stores the data.
QuCircularPlotItem::engine and QuCircularPlotWidget::engine return a reference to their QuCircularPlotEngine, that shall be used by clients to access all operations, as well as signals and slots.
Plot configuration
Plot settings are held by the qucircularplot_attributes public member named a QuCircularPlotEngine::att and QuCircularPlotEngine::attributes are convenience methods that return a (non const) reference to a.
See also
qucircularplot_attributes
Example
In this example we set up a QGraphicsPlotItem with one curve
QuCircularPlotI *ni = new QuCircularPlotI(nullptr, QSize(300, 300));
QuCircularPlotEngine *pie = ni->engine();
qucircularplot_attributes &a = pie->a;
a.axes.y.autoscale = true;  // enable y axis autoscale
a.geom.inner_radius_factor = 0.1; // widen inter axes area
a.paint.colors.background = QColor(Qt::white);  // light color scheme
ni->setObjectName("plot_" + s);
ni->setFlag(QGraphicsItem::ItemIsMovable, true);
scene->addItem(ni); // add the item to a (previously allocated) QGraphicsScene
ni->setPos(10, 10);
QuCircularPlotCurve *crv = pie->addCurve("curve 1");
QVector<double> x{0,1,2,3,4,5}, y{0.0, 0.5, -0.5, 0.4, -0.4. 0.1};
crv->setData(x, y);
// or ni->setData("curve 1", x, y);
Constructor & Destructor Documentation
QuCircularPlotEngine()
QuCircularPlotEngine::QuCircularPlotEngine (QObject * parent, const QFont & f, QuZoomer * zoomer, QuCircularPlotCurveSelectionEvents * selev, QuZoomEvents * ze) explicit
References a, clearSelection(), clicked(), QuCircularPlotEngineData::font, qucircularplot_attributes::geom, moveSelection(), qucircularplot_attributes::oob_distortion, select(), selected(), QuCircularPlotEngineData::selection_ev, QuCircularPlotEngineData::zoom_ev, QuCircularPlotEngineData::zoomer, and zoomer().
~QuCircularPlotEngine()
QuCircularPlotEngine::~QuCircularPlotEngine () virtual
References QuCircularPlotEngineData::zoom_ev, and QuCircularPlotEngineData::zoomer.
Member Function Documentation
addCurve()
QuCircularPlotCurve * QuCircularPlotEngine::addCurve (const QString & src)
References QuCircularPlotConfigurator::configure(), and QuCircularPlotEngineData::curves.
addDrawable()
void QuCircularPlotEngine::addDrawable (QuCircularPlotDrawable_I * dra)
add a QuCircularPlotDrawable_I object which will be drawn within QuCircularPlotEngine::paint according to its z position
Parameters
dra an object implementing the QuCircularPlotDrawable_I interface.
The QuCircularPlotDrawable_I::z value determines the order in which each drawable is painted. Plot background is drawn before everything else. Then drawables with negative z are drawn. Axes, bounds, curves follow. Drawables with positive z are then painted.
Drawables that scale are drawn according to the painter transformation (zoom, if applied). Those that do not scale are drawn before the transformation is applied to the painter or after the painter is restored (always according to the z position.
See also
QuCircularPlotDrawable_I
Drawables can be used to decorate the plot. For example, the y value of the selected point can be shown at the center of the plot (QuCircularPlotSelectionValue), or the plot can be divided in "sectors" (QuCircularPlotDiskSector).
References QuCircularPlotEngineData::drawables, and QuCircularPlotDrawable_I::z().
att()
qucircularplot_attributes & QuCircularPlotEngine::att ()
convenience alias for either a memeber or attributes method
Returns
a reference to the qucircularplot_attributes held by this plot
Note
a is a public member that can be directly accessed and modified by the clients
References a.
attributes()
qucircularplot_attributes & QuCircularPlotEngine::attributes ()
convenience alias for either a memeber or att method
Returns
a reference to the qucircularplot_attributes held by this plot
Note
a is a public member that can be directly accessed and modified by the clients
References a.
axesColor()
QColor QuCircularPlotEngine::axesColor () const
References a, qucircularplot_attributes::axes, qucircularplot_attributes::colors, and qucircularplot_attributes::paint.
background()
QColor QuCircularPlotEngine::background () const
References a, qucircularplot_attributes::background, qucircularplot_attributes::colors, and qucircularplot_attributes::paint.
boundingRect()
QRectF QuCircularPlotEngine::boundingRect () const
References QuCircularPlotEngineData::bounding_r.
clearSelection
void QuCircularPlotEngine::clearSelection () slot
References QuCircularPlotEngineData::curves, QuCircularPlotCurve::deselect(), dirty(), QuCircularPlotCurveSelectionEvents::select(), QuCircularPlotCurve::selected(), selectedYChanged(), and QuCircularPlotEngineData::selection_ev.
Referenced by QuCircularPlotEngine(), and setScaleInverted().
clicked
void QuCircularPlotEngine::clicked (const QPointF & p, const Qt::MouseButton butt, Qt::KeyboardModifiers mod) signal
Referenced by QuCircularPlotEngine().
closestPoint
void QuCircularPlotEngine::closestPoint (const QList< QuCircularPlotCurve * > & curves, int idx, const QPointF & pt) signal
Referenced by select().
curveEditRadius()
float QuCircularPlotEngine::curveEditRadius () const
References a, qucircularplot_attributes::aradius, qucircularplot_attributes::geom, and qucircularplot_attributes::selection.
curveSelectedPointRadius()
float QuCircularPlotEngine::curveSelectedPointRadius () const
References a, qucircularplot_attributes::geom, qucircularplot_attributes::selection, and qucircularplot_attributes::yp_radius.
dirty
void QuCircularPlotEngine::dirty () signal
Referenced by clearSelection(), moveSelection(), select(), setCurveEditRadius(), setCurveSelectionPointRadius(), setInnerRadiusFactor(), setOuterRadiusFactor(), setOutOfBoundsTransform(), setScaleInverted(), setXBounds(), setXLowerBound(), setXUpperBound(), setYBounds(), setYLowerBound(), and setYUpperBound().
drawables()
QList< QuCircularPlotDrawable_I * > QuCircularPlotEngine::drawables () const
References QuCircularPlotEngineData::drawables.
findCurve()
QuCircularPlotCurve * QuCircularPlotEngine::findCurve (const QString & src) const
find a curve either by exact match or regexp
Parameters
src the exact name of the curve (usually, its source) or a regular expression
Returns
the found curve, if any. nullptr otherwise.
First an exact match is searched using src as key. If unsuccessful, a regex based search is performed.
References QuCircularPlotEngineData::curves.
innerRadiusFactor()
float QuCircularPlotEngine::innerRadiusFactor () const
References a, qucircularplot_attributes::geom, and qucircularplot_attributes::inner_radius_factor.
maximumChanged
void QuCircularPlotEngine::maximumChanged (double M) signal
minimumChanged
void QuCircularPlotEngine::minimumChanged (double m) signal
minimumSize()
QSizeF QuCircularPlotEngine::minimumSize ()
moveSelection
void QuCircularPlotEngine::moveSelection (const double & dx, const double & dy) slot
References a, qucircularplot_attributes::axes, QuCircularPlotEngineData::bounding_r, QuCircularPlotEngineData::curves, dirty(), qucircularplot_attributes::lb, QuCircularPlotCurveSelectionEvents::select(), QuCircularPlotCurve::selected(), selectedYChanged(), QuCircularPlotEngineData::selection_ev, QuCircularPlotCurveSelectionEvents::selectionArea(), selectionChanged(), QuCircularPlotCurve::source(), qucircularplot_attributes::ub, qucircularplot_attributes::y, and QuCircularPlotCurve::y_data().
Referenced by QuCircularPlotEngine().
outerRadiusFactor()
float QuCircularPlotEngine::outerRadiusFactor () const
References a, qucircularplot_attributes::geom, and qucircularplot_attributes::outer_radius_factor.
paint()
void QuCircularPlotEngine::paint (QPainter * p, const QRectF & rect, QWidget * widget)
References a, QuZoomer::calculateTransform(), QuCircularPlotDrawable_I::draw(), QuCircularPlotEngineData::drawables, qucircularplot_attributes::geom, qucircularplot_attributes::inner_radius_factor, QuZoomer::inZoom(), qucircularplot_attributes::outer_radius_factor, QuZoomer::rectChanging(), QuCircularPlotDrawable_I::scales(), QuCircularPlotDrawable_I::z(), QuZoomer::zoomArea(), and QuCircularPlotEngineData::zoomer.
plot()
QObject * QuCircularPlotEngine::plot () const
recalculateTxtFont
void QuCircularPlotEngine::recalculateTxtFont () slot
References QuCircularPlotEngineData::bounding_r, QuCircularPlotEngineData::font, and QuCircularPlotEngineData::scaled_font.
Referenced by setFont().
scaleInverted()
bool QuCircularPlotEngine::scaleInverted () const
References a, qucircularplot_attributes::axes, qucircularplot_attributes::scale_inverted, and qucircularplot_attributes::y.
select
void QuCircularPlotEngine::select (const QPointF & p) slot
References a, qucircularplot_attributes::aradius, QuCircularPlotEngineData::bounding_r, closestPoint(), QuCircularPlotEngineData::curves, dirty(), qucircularplot_attributes::geom, qucircularplot_attributes::inner_radius_factor, qucircularplot_attributes::outer_radius_factor, qstoc, QuCircularPlotCurveSelectionEvents::select(), QuCircularPlotCurve::select(), selected(), selectedYChanged(), qucircularplot_attributes::selection, QuCircularPlotEngineData::selection_ev, QuCircularPlotCurve::source(), QuZoomer::transform(), QuCircularPlotCurve::x_data(), QuCircularPlotCurve::y_data(), and QuCircularPlotEngineData::zoomer.
Referenced by QuCircularPlotEngine().
selected
void QuCircularPlotEngine::selected (const QPointF & p) signal
Referenced by QuCircularPlotEngine(), and select().
selectedYChanged
void QuCircularPlotEngine::selectedYChanged (QuCircularPlotCurve * c) signal
selectedYChanged is emitted when a selection on one (or more) curve(s) is active and the y value for the selected curve index changes
Parameters
c the curve for which the y value changed at the selected index
Note
You can get the selected index through QuCircularPlotCurve::selected and the corresponding value accessing QuCircularPlotCurve::y_data at that index
Referenced by clearSelection(), moveSelection(), select(), and setData().
selectionChanged [1/2]
void QuCircularPlotEngine::selectionChanged (QObject * o, const QString & curve, int idx, double new_val) signal
selectionChanged [2/2]
void QuCircularPlotEngine::selectionChanged (QuCircularPlotCurve * c, int idx, double new_val) signal
Referenced by moveSelection().
setAxesColor
void QuCircularPlotEngine::setAxesColor (const QColor & c) slot
References a, qucircularplot_attributes::axes, qucircularplot_attributes::colors, and qucircularplot_attributes::paint.
setBackground
void QuCircularPlotEngine::setBackground (const QColor & c) slot
References a, qucircularplot_attributes::background, qucircularplot_attributes::colors, and qucircularplot_attributes::paint.
setCurveEditRadius
void QuCircularPlotEngine::setCurveEditRadius (float r) slot
References a, qucircularplot_attributes::aradius, dirty(), qucircularplot_attributes::geom, and qucircularplot_attributes::selection.
setCurveSelectionPointRadius
void QuCircularPlotEngine::setCurveSelectionPointRadius (float r) slot
References a, dirty(), qucircularplot_attributes::geom, qucircularplot_attributes::selection, and qucircularplot_attributes::yp_radius.
setData
void QuCircularPlotEngine::setData (const QString & src, const QVector< double > & xdata, const QVector< double > & ydata) slot
References QuCircularPlotConfigurator::configure(), QuCircularPlotEngineData::curves, QuCircularPlotCurve::selected(), selectedYChanged(), QuCircularPlotCurve::setData(), QuCircularPlotCurve::size(), and QuCircularPlotCurve::y_data().
setFont()
void QuCircularPlotEngine::setFont (const QFont & f)
References QuCircularPlotEngineData::font, and recalculateTxtFont().
setInnerRadiusFactor
void QuCircularPlotEngine::setInnerRadiusFactor (float f) slot
References a, dirty(), qucircularplot_attributes::geom, and qucircularplot_attributes::inner_radius_factor.
setOuterRadiusFactor
void QuCircularPlotEngine::setOuterRadiusFactor (float f) slot
References a, dirty(), qucircularplot_attributes::geom, and qucircularplot_attributes::outer_radius_factor.
setOutOfBoundsTransform()
void QuCircularPlotEngine::setOutOfBoundsTransform (OOBDistort * c)
References a, dirty(), qucircularplot_attributes::geom, and qucircularplot_attributes::oob_distortion.
setScaleInverted
void QuCircularPlotEngine::setScaleInverted (bool inve) slot
References a, qucircularplot_attributes::axes, clearSelection(), dirty(), qucircularplot_attributes::scale_inverted, and qucircularplot_attributes::y.
setShowBounds
void QuCircularPlotEngine::setShowBounds (bool show) slot
References a, qucircularplot_attributes::paint, and qucircularplot_attributes::show_bounds.
setShowCurves
void QuCircularPlotEngine::setShowCurves (bool show) slot
References a, qucircularplot_attributes::paint, and qucircularplot_attributes::show_curves.
setShowPoints
void QuCircularPlotEngine::setShowPoints (bool show) slot
References a, qucircularplot_attributes::paint, and qucircularplot_attributes::show_points.
setShowValues
void QuCircularPlotEngine::setShowValues (bool show) slot
References a, qucircularplot_attributes::paint, and qucircularplot_attributes::show_values.
setShowYAxes
void QuCircularPlotEngine::setShowYAxes (int count) slot
References a, qucircularplot_attributes::paint, and qucircularplot_attributes::y_axes.
setXAutoscaleEnabled
void QuCircularPlotEngine::setXAutoscaleEnabled (bool en) slot
enable or disable the x axis autoscale
Parameters
en true autoscale is enabled and the x scale is updated immediately according to the bounds of all the curves
en false autoscale is disabled. Current x axis bounds are left untouched
Note
For the x axis, it is assumed that x values are odered from smallest to greatest
References a, qucircularplot_attributes::autoscale, qucircularplot_attributes::axes, and qucircularplot_attributes::x.
setXBounds
void QuCircularPlotEngine::setXBounds (double xm, double xM) slot
References a, qucircularplot_attributes::autoscale, qucircularplot_attributes::axes, dirty(), qucircularplot_attributes::lb, qucircularplot_attributes::ub, and qucircularplot_attributes::x.
setXLowerBound
void QuCircularPlotEngine::setXLowerBound (double m) slot
disable x axis autoscale and set the lower bound
Parameters
m new lower bound
References a, qucircularplot_attributes::autoscale, qucircularplot_attributes::axes, dirty(), qucircularplot_attributes::lb, and qucircularplot_attributes::x.
setXUpperBound
void QuCircularPlotEngine::setXUpperBound (double m) slot
disable x axis autoscale and set the upper bound
Parameters
m new upper bound
References a, qucircularplot_attributes::autoscale, qucircularplot_attributes::axes, dirty(), qucircularplot_attributes::ub, and qucircularplot_attributes::x.
setYAutoscaleEnabled
void QuCircularPlotEngine::setYAutoscaleEnabled (bool en) slot
enable or disable the y axis autoscale
Parameters
en true autoscale is enabled and the y scale is updated immediately according to the bounds of all the curves
en false autoscale is disabled. Current y axis bounds are left untouched
References a, qucircularplot_attributes::autoscale, qucircularplot_attributes::axes, and qucircularplot_attributes::y.
setYBounds
void QuCircularPlotEngine::setYBounds (double ym, double yM) slot
References a, qucircularplot_attributes::autoscale, qucircularplot_attributes::axes, dirty(), qucircularplot_attributes::lb, qucircularplot_attributes::ub, and qucircularplot_attributes::y.
setYLowerBound
void QuCircularPlotEngine::setYLowerBound (double m) slot
disable y axis autoscale and set the lower bound
Parameters
m new lower bound
References a, qucircularplot_attributes::autoscale, qucircularplot_attributes::axes, dirty(), qucircularplot_attributes::lb, and qucircularplot_attributes::y.
setYUpperBound
void QuCircularPlotEngine::setYUpperBound (double m) slot
disable y axis autoscale and set the upper bound
Parameters
m new upper bound
References a, qucircularplot_attributes::autoscale, qucircularplot_attributes::axes, dirty(), qucircularplot_attributes::ub, and qucircularplot_attributes::y.
showBounds()
bool QuCircularPlotEngine::showBounds () const
References a, qucircularplot_attributes::paint, and qucircularplot_attributes::show_bounds.
showCurves()
bool QuCircularPlotEngine::showCurves () const
References a, qucircularplot_attributes::paint, and qucircularplot_attributes::show_curves.
showPoints()
bool QuCircularPlotEngine::showPoints () const
References a, qucircularplot_attributes::paint, and qucircularplot_attributes::show_points.
showValues()
bool QuCircularPlotEngine::showValues () const
References a, qucircularplot_attributes::paint, and qucircularplot_attributes::show_values.
showXAxis()
bool QuCircularPlotEngine::showXAxis () const
References a, qucircularplot_attributes::paint, and qucircularplot_attributes::show_xax.
showYAxes()
int QuCircularPlotEngine::showYAxes () const
References a, qucircularplot_attributes::paint, and qucircularplot_attributes::y_axes.
xLowerBound()
double QuCircularPlotEngine::xLowerBound () const
References a, qucircularplot_attributes::axes, qucircularplot_attributes::lb, and qucircularplot_attributes::x.
xUpperBound()
double QuCircularPlotEngine::xUpperBound () const
References a, qucircularplot_attributes::axes, qucircularplot_attributes::ub, and qucircularplot_attributes::x.
yLowerBound()
double QuCircularPlotEngine::yLowerBound () const
References a, qucircularplot_attributes::axes, qucircularplot_attributes::lb, and qucircularplot_attributes::y.
yUpperBound()
double QuCircularPlotEngine::yUpperBound () const
References a, qucircularplot_attributes::axes, qucircularplot_attributes::ub, and qucircularplot_attributes::y.
zoomer()
QuZoomer * QuCircularPlotEngine::zoomer () const
References QuCircularPlotEngineData::zoomer.
Referenced by QuCircularPlotEngine().
zoomEvents()
QuZoomEvents * QuCircularPlotEngine::zoomEvents () const
References QuCircularPlotEngineData::zoom_ev.
Member Data Documentation
a
struct qucircularplot_attributes QuCircularPlotEngine::a
plot configuration
See also
qucircularplot_attributes
Referenced by att(), attributes(), axesColor(), background(), curveEditRadius(), curveSelectedPointRadius(), innerRadiusFactor(), moveSelection(), outerRadiusFactor(), paint(), QuCircularPlotEngine(), scaleInverted(), select(), setAxesColor(), setBackground(), setCurveEditRadius(), setCurveSelectionPointRadius(), setInnerRadiusFactor(), setOuterRadiusFactor(), setOutOfBoundsTransform(), setScaleInverted(), setShowBounds(), setShowCurves(), setShowPoints(), setShowValues(), setShowYAxes(), setXAutoscaleEnabled(), setXBounds(), setXLowerBound(), setXUpperBound(), setYAutoscaleEnabled(), setYBounds(), setYLowerBound(), setYUpperBound(), showBounds(), showCurves(), showPoints(), showValues(), showXAxis(), showYAxes(), xLowerBound(), xUpperBound(), yLowerBound(), and yUpperBound().
The documentation for this class was generated from the following files:
qucircularplotengine.h
qucircularplotengine.cpp